logisim-evolution/logisim-evolution

src/com/bfh/logisim/settings/Settings.java

I've removed some code that is only usefull inside hepia's domain

Remove hepia specific code

---

resources/logisim/es/log.properties
resources/logisim/es/menu.properties

"Registro" is an incorrect word and should be "Cronograma" (the Spanish translation of chronogram)

Updated chronogram translations

---

README.md

Corrects a typo ("udpates" -> "updates"), and a minor grammar improvement towards the bottom. :)

README.md: correct typo

---

src/com/cburch/logisim/Main.java
src/com/cburch/logisim/prefs/AppPreferences.java

There was an issue which I had at #166. I found a method which fixed it which was just to have an extra check to make sure it did not make any gui calls in headless.

Hacky patch to the headless issue

---

src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/gui/prefs/SoftwaresOptions.java
src/main/java/com/cburch/logisim/gui/start/Startup.java
src/main/java/com/cburch/logisim/prefs/AppPreferences.java
src/main/resources/resources/logisim/en/prefs.properties

The first time logisim is started it will ask if auto-update check
should be performed.

Checking for software updates is now handled in the preferences.

---

src/main/java/com/cburch/logisim/analyze/file/AnalyzerTexWriter.java
src/main/java/com/cburch/logisim/analyze/gui/VariableTab.java
src/main/java/com/cburch/logisim/util/LocaleManager.java
src/main/resources/resources/logisim/de/analyze.properties
src/main/resources/resources/logisim/de/util.properties
src/main/resources/resources/logisim/en/analyze.properties
src/main/resources/resources/logisim/en/util.properties
src/main/resources/resources/logisim/fr/analyze.properties
src/main/resources/resources/logisim/fr/util.properties

and german. It seems that JFileChooser and JOptionPane do not react
anymore correctly on locale settings (they are always in english).

Small bugfix on push from mbaillif and added multi-language for french

---

src/main/resources/resources/logisim/es/hdl.properties
src/main/resources/resources/logisim/fr/fpga.properties
src/main/resources/resources/logisim/fr/std.properties
src/main/resources/resources/logisim/nl/fpga.properties

French translation

---

src/main/java/com/cburch/logisim/gui/main/Canvas.java
src/main/java/com/cburch/logisim/util/SmartScroller.java

I fixed it to automatically pan into the direction of the mouse if the latter hits the screen border while one is wiring or placing components. Pretty cool enhancement. Saves you the hustle.

fixed Auto-pan while wiring or placing components #255

---

src/main/java/com/cburch/logisim/gui/start/Startup.java

Original prompt had grammatical issues and language abnormalities.

Revised the first-time startup autoupdate window text

---

src/main/java/com/cburch/logisim/gui/generic/RegTabContent.java
src/main/java/com/cburch/logisim/util/AlphanumComparator.java

-Use monospaced font for register values in State view (ffff and 0000 differ a lot in large register)
-Use "natural" sorting for register names: R1, R2,..., R10 instead of R1, R10, R2 etc.

State view improvements

---

src/main/java/com/cburch/logisim/gui/start/Startup.java

Fix hang after run with -tty

---

README.md

This PR is purposely done on the [master branch](https://github.com/reds-heig/logisim-evolution/tree/master) to fix quickly the issues #96 and #363 for new Logisim-evolution users. After merging, the fix should be merged into the [develop branch](https://github.com/reds-heig/logisim-evolution/tree/develop) branch as well using:
```
git checkout master
git pull origin
git checkout develop
git pull origin
git merge master
git push origin develop
```

Fix issues #96 and #363 by updating broken links in README.md

---

src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java
src/main/java/com/cburch/logisim/fpga/prefs/FPGAOptions.java
src/main/java/com/cburch/logisim/prefs/AppPreferences.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorBoolean.java
src/main/java/com/cburch/logisim/std/arith/MultiplierHDLGeneratorFactory.java
src/main/resources/resources/logisim/en/fpga.properties

Fixed multiplier VHDL generator and added multiplier Verilog generator.

Added option to switchoff gated-clock and open-pin warnings.

---

src/main/java/com/cburch/logisim/data/BitWidth.java
src/main/java/com/cburch/logisim/data/Value.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/AbstractHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/CircuitHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/prefs/FPGABoards.java
src/main/java/com/cburch/logisim/std/io/PortHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/std/io/PortIO.java
src/main/java/com/cburch/logisim/std/io/ReptarLocalBus.java
src/main/resources/resources/logisim/de/std.properties
src/main/resources/resources/logisim/el/std.properties
src/main/resources/resources/logisim/en/std.properties
src/main/resources/resources/logisim/es/std.properties
src/main/resources/resources/logisim/fr/std.properties
src/main/resources/resources/logisim/it/std.properties
src/main/resources/resources/logisim/nl/std.properties
src/main/resources/resources/logisim/pt/std.properties
src/main/resources/resources/logisim/ru/std.properties

Fixed several small bugs in the verilog generation.

Merged PORTIO changes from Kevin Walsh to provide IO-pins.

---

src/main/resources/doc/de/html/guide/verify/test.html
src/main/resources/doc/en/html/guide/verify/test.html
src/main/resources/doc/pt/html/guide/verify/test.html
src/main/resources/doc/ru/html/guide/verify/test.html

Simple PR to update spelling in documentation,

Corrected Typo in Documentation --  "Vactor" to "Vector"

---

src/main/java/com/cburch/logisim/std/io/extra/Buzzer.java

Fixes #470 
Current problems:
- the sound cuts for a few milliseconds when volume or frequency are changed while playing

Experimental support for simultaneously playing buzzers

---

build.gradle.kts
src/main/java/com/cburch/draw/tools/TextTool.java
src/main/java/com/cburch/hex/Caret.java
src/main/java/com/cburch/logisim/analyze/gui/TableTabCaret.java
src/main/java/com/cburch/logisim/comp/TextFieldCaret.java
src/main/java/com/cburch/logisim/file/Loader.java
src/main/java/com/cburch/logisim/gui/chronogram/chronogui/RightPanel.java
src/main/java/com/cburch/logisim/gui/main/KeyboardToolSelection.java
src/main/java/com/cburch/logisim/gui/main/LayoutToolbarModel.java
src/main/java/com/cburch/logisim/gui/menu/MenuEdit.java
src/main/java/com/cburch/logisim/gui/menu/MenuFile.java
src/main/java/com/cburch/logisim/gui/menu/MenuSimulate.java
src/main/java/com/cburch/logisim/instance/InstanceLoggerAdapter.java
src/main/java/com/cburch/logisim/instance/InstancePokerAdapter.java
src/main/java/com/cburch/logisim/tools/FactoryDescription.java
src/main/java/com/cburch/logisim/tools/SelectTool.java
src/main/java/com/cburch/logisim/util/InputEventUtil.java
src/main/java/com/cburch/logisim/util/TextLineNumber.java
src/main/java/com/cburch/logisim/util/WindowMenu.java
src/main/java/com/cburch/logisim/vhdl/gui/VhdlSimulatorConsole.java

This PR fixes all deprecations reported by the Java compiler when `-Xlint:deprecation` is passed.

Fix deprecations

---

gradle.properties
src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/fpga/designrulecheck/ClockSourceContainer.java
src/main/java/com/cburch/logisim/std/wiring/ClockHDLGeneratorFactory.java

Added phased clock to HDL generator

---

src/main/java/com/cburch/logisim/std/base/Base.java
src/main/java/com/cburch/logisim/std/memory/Ram.java
src/main/java/com/cburch/logisim/std/memory/RomHDLGeneratorFactory.java

Fixed #545

---

src/main/java/com/cburch/logisim/gui/generic/ProjectExplorer.java
src/main/java/com/cburch/logisim/gui/generic/ProjectExplorerLibraryNode.java
src/main/java/com/cburch/logisim/gui/generic/ProjectExplorerModel.java
src/main/java/com/cburch/logisim/gui/main/Toolbox.java
src/main/java/com/cburch/logisim/gui/opts/MouseOptions.java
src/main/java/com/cburch/logisim/gui/opts/ToolbarOptions.java

Base again available for template and mouse

---

.github/workflows/gradle.yml
README.md
src/main/java/com/cburch/logisim/gui/main/SelectionActions.java

This PR also updates the master branch to the latest 3.4.5 code.

Fix #557 (can't copy labels); add GitHub actions CI

---

src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java

Tidy previous implementation and improve ripple logic

Tidy up ripple and validate

---

src/main/java/com/cburch/logisim/std/io/DotMatrix.java
src/main/java/com/cburch/logisim/std/io/DotMatrixHDLGeneratorFactory.java

DotMatrixes lacked either the rows or columns port when:
- the _Input Format_ is _Select Rows/Columns_ 
and
- the number of columns or rows is 1
Before:
After:

Fixed missing port on DotMatrix

---

src/main/resources/resources/logisim/strings/data/data.properties
src/main/resources/resources/logisim/strings/data/data_de.properties
src/main/resources/resources/logisim/strings/data/data_el.properties
src/main/resources/resources/logisim/strings/data/data_es.properties
src/main/resources/resources/logisim/strings/data/data_fr.properties
src/main/resources/resources/logisim/strings/data/data_it.properties
src/main/resources/resources/logisim/strings/data/data_ja.properties
src/main/resources/resources/logisim/strings/data/data_nl.properties
src/main/resources/resources/logisim/strings/data/data_pt.properties
src/main/resources/resources/logisim/strings/data/data_ru.properties

Augments direction verbal labels with corresponding arrow symbols, as pictograms are processable faster and are more intuitive  for i.e. younger users.

Augments direction verbal labels with corresponding arrow symbols

---

src/main/java/com/cburch/logisim/std/io/DipSwitch.java

Adds DIP switch state visual feedback and paints active switch background with `TRUE_COLOR`:

Adds DIP switch state visual feedback

---

src/main/resources/resources/logisim/settings.properties

Removes `pl` from list of supported locales as there's no Polish translation available.

Updates list of supported locale

---

src/main/java/com/cburch/logisim/gui/prefs/WindowOptions.java
src/main/java/com/cburch/logisim/prefs/AppPreferences.java
src/main/resources/resources/logisim/strings/gui/gui.properties

Add option to restore default grid colors directly in Preferences -> Window

Add option to restore default grid colors

---

CHANGES.md

Adds CHANGELOG.md to the project. Every new PR should add related entry here as well.

Adds CHANGELOG.md to the project

---

src/main/java/com/cburch/logisim/gui/hex/HexFile.java

The current code uses Long.parseLong(text, 16) to parse hex words that are taken from .circ files, at least for the ROM. It fails (and skips the word) when the 63rd bit of the word is a 1, since it is a not written with a - sign and it is too big to fit in a signed Long as a positive number.
This PR uses Long.parseUnsignedLong(text,16) to parse those hex words. Since I don't know if there is ever a word with + or - signs in the file, the code tries the original Long.parseLong(text,16) if the unsigned version fails. Thus it should work for all cases that it worked for before this PR.
I noticed in testing that the use of a negative replication amount causes the whole file read to throw an exception. So I changed the Long.parseLong(text) to read the replication amount to …

Fix problem reading hex values from saved .circ files with a 1 in bit 63.

---

src/main/java/com/cburch/logisim/vhdl/syntax/VhdlSyntax.flex
src/main/java/com/cburch/logisim/vhdl/syntax/VhdlSyntax.java

Added a warning to auto-generated files as temporary workaround #563

Added warning header to autogenerated files

---

src/main/java/com/cburch/logisim/circuit/Splitter.java
src/main/java/com/cburch/logisim/circuit/SplitterFactory.java
src/main/java/com/cburch/logisim/file/LogisimFile.java
src/main/java/com/cburch/logisim/file/XmlReader.java
src/main/java/com/cburch/logisim/gui/main/LayoutEditHandler.java
src/main/java/com/cburch/logisim/gui/main/ToolboxManip.java
src/main/java/com/cburch/logisim/gui/start/Startup.java
src/main/java/com/cburch/logisim/std/base/Base.java
src/main/java/com/cburch/logisim/std/gates/Gates.java
src/main/java/com/cburch/logisim/tools/AddTool.java
src/main/java/com/cburch/logisim/tools/EditTool.java
src/main/java/com/cburch/logisim/tools/Library.java
src/main/java/com/cburch/logisim/tools/MenuTool.java
src/main/java/com/cburch/logisim/tools/PokeTool.java
src/main/java/com/cburch/logisim/tools/SelectTool.java
src/main/java/com/cburch/logisim/tools/TextTool.java
src/main/java/com/cburch/logisim/tools/Tool.java
src/main/java/com/cburch/logisim/tools/WiringTool.java

Adds _ID to remaining libraries and tools and replaces hardcoded references with use of corresponding IDs.

Adds _ID to remaining libraries and tools

---

src/main/java/com/cburch/gray/Components.java
src/main/java/com/cburch/logisim/fpga/library/BFHPraktika.java
src/main/java/com/cburch/logisim/soc/Soc.java
src/main/java/com/cburch/logisim/std/Builtin.java
src/main/java/com/cburch/logisim/std/arith/Arithmetic.java
src/main/java/com/cburch/logisim/std/hdl/Hdl.java
src/main/java/com/cburch/logisim/std/io/Io.java
src/main/java/com/cburch/logisim/std/io/extra/ITA_IO.java
src/main/java/com/cburch/logisim/std/memory/Memory.java
src/main/java/com/cburch/logisim/std/plexers/Plexers.java
src/main/java/com/cburch/logisim/std/tcl/Tcl.java
src/main/java/com/cburch/logisim/std/ttl/TTL.java
src/main/java/com/cburch/logisim/std/wiring/Wiring.java

Restored library _IDs formerly introduced in #648 and somehow gone in meantime.
See #680  for details

Restored library _IDs

---

src/main/java/com/cburch/logisim/fpga/data/MapComponent.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/AbstractHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/CircuitHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/HDL.java
src/main/java/com/cburch/logisim/std/gates/AbstractGateHDLGenerator.java
src/main/java/com/cburch/logisim/std/gates/AndGate.java
src/main/java/com/cburch/logisim/std/gates/NandGate.java
src/main/java/com/cburch/logisim/std/gates/NorGate.java
src/main/java/com/cburch/logisim/std/gates/OrGate.java

* Replaced mixed string concatenation with chained StringBuffer's append() calls
* Simplified certain code assignments logic

Performance optimizations

---

build.gradle.kts
src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java
src/main/java/com/cburch/logisim/soc/util/AssemblerInfo.java

`appName` is never altered once assigned, so it can be sealed as `val`. 
@davidhutchens can you take a look?

Sealed appName gradle variable

---

src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java
src/main/java/com/cburch/logisim/gui/menu/MenuHelp.java
src/main/java/com/cburch/logisim/gui/start/AboutCredits.java
src/main/java/com/cburch/logisim/soc/util/AssemblerInfo.java
src/main/resources/resources/logisim/strings/gui/gui.properties
src/main/resources/resources/logisim/strings/gui/gui_de.properties
src/main/resources/resources/logisim/strings/gui/gui_el.properties
src/main/resources/resources/logisim/strings/gui/gui_es.properties
src/main/resources/resources/logisim/strings/gui/gui_fr.properties
src/main/resources/resources/logisim/strings/gui/gui_it.properties
src/main/resources/resources/logisim/strings/gui/gui_ja.properties
src/main/resources/resources/logisim/strings/gui/gui_nl.properties
src/main/resources/resources/logisim/strings/gui/gui_pt.properties
src/main/resources/resources/logisim/strings/gui/gui_ru.properties

Restored Help menu + About credits formerly introduced in #650
Re: #680 action

RestoresHelp menu + About credits changes

---

build.gradle.kts
checkstyle/google_checks.xml
src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java
src/main/java/com/cburch/logisim/soc/util/AssemblerInfo.java

Adds CheckStyle coding style checked to Gradle, with "google-java" style set as default. This is basically the first step to have code style checked as Github Action. 
Usage:  `./gradlew checkstyleMain`

Adds CheckStyle coding style checked to Gradle

---

CHANGES.md
README.md
build.gradle.kts
src/main/java/com/cburch/logisim/gui/start/About.java
src/main/java/com/cburch/logisim/gui/start/AboutCredits.java
src/main/java/com/cburch/logisim/gui/start/AppLogo.java
src/main/java/com/cburch/logisim/gui/start/SplashScreen.java
src/main/resources/resources/logisim/img/logisim-evolution-logo.svg

* Added project logo
* Updated About dialog to show it (renders with Batik)
* Added logo to README
* Significantly reduced over-engineered  credits scroll code

Project logo

---

src/main/java/com/cburch/logisim/LogisimVersion.java
src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/circuit/Circuit.java
src/main/java/com/cburch/logisim/gui/main/AttrTableSelectionModel.java
src/main/java/com/cburch/logisim/std/ttl/AbstractGateHDLGenerator.java
src/main/java/com/cburch/logisim/tools/AddTool.java
src/main/java/com/cburch/logisim/tools/SelectTool.java
src/main/java/com/cburch/logisim/util/AlphanumComparator.java
src/main/java/com/cburch/logisim/util/AutoLabel.java
src/main/java/com/cburch/logisim/util/CollectionUtil.java
src/main/java/com/cburch/logisim/util/GifEncoder.java
src/main/java/com/cburch/logisim/util/GraphicsUtil.java
src/main/java/com/cburch/logisim/util/Icons.java
src/main/java/com/cburch/logisim/util/InputEventUtil.java
src/main/java/com/cburch/logisim/util/JDialogOk.java
src/main/java/com/cburch/logisim/util/JFileChoosers.java
src/main/java/com/cburch/logisim/util/LocaleManager.java
src/main/java/com/cburch/logisim/util/OutputStreamBinarySanitizer.java
src/main/java/com/cburch/logisim/util/OutputStreamEscaper.java
src/main/java/com/cburch/logisim/util/SocketClient.java
src/main/java/com/cburch/logisim/util/SyntaxChecker.java
src/main/java/com/cburch/logisim/util/TextLineNumber.java
src/main/java/com/cburch/logisim/util/WindowMenu.java

As part of #698 this one addresses most of fixable coding style issues with "util/"

Corrected some coding style offences in "util/"

---

src/main/java/com/cburch/logisim/soc/data/SocBusTransaction.java
src/main/java/com/cburch/logisim/soc/file/ElfProgramHeader.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2ArithmeticAndLogicalInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2ComparisonInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2DataTransferInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2OtherControlInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2ProgramControlInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2ShiftAndRotateInstructions.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2Support.java
src/main/java/com/cburch/logisim/soc/pio/PioState.java
src/main/java/com/cburch/logisim/soc/rv32im/RV32imControlTransferInstructions.java
src/main/java/com/cburch/logisim/soc/rv32im/RV32imIntegerRegisterImmediateInstructions.java
src/main/java/com/cburch/logisim/soc/rv32im/RV32imIntegerRegisterRegisterOperations.java
src/main/java/com/cburch/logisim/soc/rv32im/RV32imLoadAndStoreInstructions.java
src/main/java/com/cburch/logisim/soc/rv32im/RV32im_M_ExtensionInstructions.java
src/main/java/com/cburch/logisim/soc/util/AbstractAssembler.java

Completes reformatting of `com/cburch/logisim/soc/*` as per [this comment](https://github.com/logisim-evolution/logisim-evolution/issues/698#issuecomment-866980425)
Ref: #698

Completes reformatting of `com/cburch/logisim/soc/*`

---

src/main/java/com/cburch/logisim/tools/AddTool.java
src/main/java/com/cburch/logisim/tools/PokeTool.java
src/main/java/com/cburch/logisim/tools/WiringTool.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlEntity.java
src/main/java/com/cburch/logisim/vhdl/gui/HdlContentEditor.java

Code style fixes:
```
src/main/java/com/cburch/logisim/tools/*
src/main/java/com/cburch/logisim/vhdl/*
```
Ref: #698

Style fies for tools and vhdl packages

---

.github/workflows/gradle.yml

Changes:
* removed "push" trigger on "develop" branch - we should not have any direct pushes, but pull requests
* build is skipped if no file under `src/**` is altered

Run build action only when anything is changed under src/**

---

README.md
docs/credits.md
docs/developers.md
docs/docs.md
docs/pics.md
docs/style.md

Clicking the banner now leads to the GitHub page and not to the source file.

Banner links to Projekt page

---

src/main/resources/resources/logisim/default.templ

Forgot to change it back in #688.

fixed BFH library reference

---

tools/syncTranslations.py

@MarcinOrlowski asked if I could share the script, I used for #759.
Here it is. Since I didn't spend much time on it, there is definitely room for improvement.

Added syncTranslations script

---

.github/workflows/build.yml

This PR fixes Gradle builder action not working fully properly, incl. skipping jobs when in fact build was needed.

Reworked builder action

---

.github/workflows/checkstyle.yml

Adds Checkstyle lint action that runs checkstyle linter against source files being part of submitted PR.

Adds Checkstyle lint action

---

README.md
docs/credits.md
docs/developers.md
docs/docs.md
docs/style.md

These are the edits I said I would do in #764.

Improve English flow in README and related files

---

.github/workflows/checkstyle.yml
.github/workflows/markdown.yml

Improved GH Actions by renaming jobs and adding step names.

Improved GH Actions

---

README.md
docs/credits.md

**EDIT:** Since this PR consists of really small changes with not so descriptive commit messages, I would advise squashing it before merge

Fix typo in README, update CREDITS.md

---

.github/workflows/build.yml
README.md
artwork/README.md
build.gradle.kts
docs/developers.md
docs/docs.md

Increases min JDK version to 14. 
Closes #789

Increases min JDK version to 14. Closes #789

---

CHANGES.md
src/main/java/com/cburch/logisim/fpga/gui/ZoomSlider.java
src/main/java/com/cburch/logisim/gui/appear/AppearanceView.java
src/main/java/com/cburch/logisim/gui/generic/BasicZoomModel.java
src/main/java/com/cburch/logisim/gui/generic/CanvasPane.java
src/main/java/com/cburch/logisim/gui/generic/ZoomControl.java
src/main/java/com/cburch/logisim/gui/generic/ZoomModel.java
src/main/java/com/cburch/logisim/gui/main/Canvas.java
src/main/java/com/cburch/logisim/gui/main/Frame.java
src/main/resources/resources/logisim/strings/gui/gui.properties
src/main/resources/resources/logisim/strings/gui/gui_de.properties
src/main/resources/resources/logisim/strings/gui/gui_el.properties
src/main/resources/resources/logisim/strings/gui/gui_es.properties
src/main/resources/resources/logisim/strings/gui/gui_it.properties
src/main/resources/resources/logisim/strings/gui/gui_ja.properties
src/main/resources/resources/logisim/strings/gui/gui_nl.properties
src/main/resources/resources/logisim/strings/gui/gui_pl.properties
src/main/resources/resources/logisim/strings/gui/gui_pt.properties
src/main/resources/resources/logisim/strings/gui/gui_ru.properties

Reworked Zoom controls for wider ranges and better granularity. Also added quick zoom buttons and change the way zoom value is shown.
Closes #254

Reworked Zoom controls. Closes #254

---

.github/workflows/nightly.yml
README.md
build.gradle.kts

Adds experimental nightly builder. More in ticket: #818
Squash merge recommended.

Adds nightly builds.

---

src/main/java/com/cburch/logisim/std/memory/ShiftRegister.java

Fix misaligned pin in shift-register

---

src/main/java/com/cburch/logisim/fpga/hdlgenerator/FileWriter.java

Fixed wrong header for Verilog file

---

src/main/java/com/cburch/logisim/soc/rv32im/RV32imControlTransferInstructions.java

Fixed bug in Risc-V simulator reported in issue #867.

---

src/main/java/com/cburch/logisim/file/XmlWriter.java
src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java

bug fix for issue #526 (Splitter loop gives different results in simulation and on FPGA board)

---

src/main/java/com/cburch/logisim/analyze/model/Expression.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/HDL.java
src/main/java/com/cburch/logisim/gui/chrono/LeftPanel.java
src/main/java/com/cburch/logisim/gui/chrono/RightPanel.java
src/main/java/com/cburch/logisim/gui/main/Canvas.java
src/main/java/com/cburch/logisim/soc/data/SocBusMasterInterface.java
src/main/java/com/cburch/logisim/soc/data/SocBusSlaveListener.java
src/main/java/com/cburch/logisim/soc/data/SocBusSnifferInterface.java
src/main/java/com/cburch/logisim/std/arith/FPAdder.java
src/main/java/com/cburch/logisim/std/arith/FPComparator.java
src/main/java/com/cburch/logisim/std/arith/FPDivider.java
src/main/java/com/cburch/logisim/std/arith/FPMultiplier.java
src/main/java/com/cburch/logisim/std/arith/FPNegator.java
src/main/java/com/cburch/logisim/std/arith/FPSubtractor.java
src/main/java/com/cburch/logisim/std/arith/IntToFP.java
src/main/java/com/cburch/logisim/std/gates/CircuitDetermination.java
src/main/java/com/cburch/logisim/std/io/Video.java
src/main/java/com/cburch/logisim/std/memory/Mem.java
src/main/java/com/cburch/logisim/std/memory/RamAppearance.java
src/main/java/com/cburch/logisim/std/tcl/TclComponent.java
src/main/java/com/cburch/logisim/std/ttl/AbstractTtlGate.java
src/main/java/com/cburch/logisim/std/ttl/Drawgates.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java
src/main/java/com/cburch/logisim/util/AutoLabel.java
src/main/java/com/cburch/logisim/util/LibraryUtil.java

Another take to make Checkstyle more happy.

Addressed Checkstyle complaints

---

src/main/java/com/cburch/logisim/LogisimVersion.java
src/test/java/com/cburch/logisim/LogisimVersionTest.java

Makes LogisimVersion class understand optional version suffix (i.e. `3.6.0-beta1`).

Adds version suffix to LogisimVersion class 

---

build.gradle.kts

Yesterday during merging #907 I wrongly solved the conflict in build.gradle.kts. This PR fixes that problem.

Wrong correction of merge conflict 

---

src/main/java/com/cburch/logisim/data/Location.java
src/main/java/com/cburch/logisim/soc/memory/SocMemoryState.java
src/main/java/com/cburch/logisim/soc/nios2/Nios2State.java
src/main/java/com/cburch/logisim/std/ttl/Drawgates.java
src/main/java/com/cburch/logisim/std/ttl/Ttl7451.java
src/main/java/com/cburch/logisim/std/ttl/Ttl7458.java
src/main/java/com/cburch/logisim/std/ttl/Ttl7464.java

Corrects codestyle, some `final var` + a few refactorings to use switch expr.
BLOCKED_BY #940

Corrects codestyle

---

.github/workflows/translations.yml

#937 got merged before I could add the improvments suggested by @MarcinOrlowski.

make use of trans-tool 2.4 features

---

src/main/java/com/cburch/logisim/fpga/data/MapComponent.java
src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/CircuitHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/std/gates/AbstractGateHDLGenerator.java

Fixed typo in word "Bubble" used in var and method names.

Fixed typo in word "Bubble"

---

src/main/java/com/cburch/logisim/util/LineBuffer.java
src/test/java/com/cburch/logisim/LineBufferTest.java

Fixed handling of multiple placeholders in one line

---

src/main/java/com/cburch/logisim/std/memory/ShiftRegister.java

This PR fixes the bug reported in #836

Java exception in Shift Register. Fixes #836

---

src/main/java/com/cburch/logisim/util/LibraryUtil.java

Fix jar library loading problem

---

src/main/java/com/cburch/logisim/util/LibraryUtil.java

Addresses #1000 on develop branch

same as #1001 but now for develop

---

.github/workflows/build.yml
.github/workflows/nightly.yml
build.gradle.kts
docs/developers.md

As per talk #951 this PR bumps JDK to v16.
DEPENDS_ON #974

Bumps JDK to v16

---

src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/circuit/Circuit.java
src/main/java/com/cburch/logisim/circuit/CircuitWires.java
src/main/java/com/cburch/logisim/circuit/ReplacementMap.java
src/main/java/com/cburch/logisim/fpga/data/MappableResourcesContainer.java
src/main/java/com/cburch/logisim/fpga/file/BoardReaderClass.java
src/main/java/com/cburch/logisim/prefs/Template.java
src/main/java/com/cburch/logisim/tools/move/SearchNode.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlSimConstants.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTop.java

This PR removes unused instances of `slf4j` logger and corrects cross use of logger instances.

Logger instances house keeping

---

src/main/java/com/cburch/logisim/gui/start/Startup.java

Fixes CLI argument parser config that was incorrect for certain options.
Closes #1010

Fixes CLI argument parser config

---

src/main/java/com/cburch/logisim/gui/start/Startup.java

Increased CLI help line width to 100 chars

---

src/main/resources/resources/logisim/strings/gui/gui_nl.properties
src/main/resources/resources/logisim/strings/std/std_nl.properties

added some dutch translations

---

.github/workflows/nightly.yml

Removed explicit JAVA_HOME setup on macOS nighty builder

---

src/main/java/com/cburch/logisim/circuit/Circuit.java
src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java

First pass in cleanup netlist and bugfix for #1028

---

src/main/java/com/cburch/logisim/circuit/Circuit.java
src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java

This is the same bugfix as #1035, but now for the v3.6.0

Netlist bugfix for v3.6.0

---

CHANGES.md
src/main/java/com/cburch/logisim/circuit/Circuit.java
src/main/java/com/cburch/logisim/circuit/CircuitAttributes.java
src/main/java/com/cburch/logisim/circuit/Simulator.java
src/main/java/com/cburch/logisim/fpga/gui/FPGAClockPanel.java
src/main/java/com/cburch/logisim/fpga/gui/FPGACommander.java
src/main/java/com/cburch/logisim/fpga/hdlgenerator/CircuitHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/gui/start/Startup.java
src/main/java/com/cburch/logisim/proj/Project.java
src/main/resources/resources/logisim/strings/circuit/circuit.properties
src/main/resources/resources/logisim/strings/circuit/circuit_de.properties
src/main/resources/resources/logisim/strings/circuit/circuit_el.properties
src/main/resources/resources/logisim/strings/circuit/circuit_es.properties
src/main/resources/resources/logisim/strings/circuit/circuit_fr.properties
src/main/resources/resources/logisim/strings/circuit/circuit_it.properties
src/main/resources/resources/logisim/strings/circuit/circuit_ja.properties
src/main/resources/resources/logisim/strings/circuit/circuit_nl.properties
src/main/resources/resources/logisim/strings/circuit/circuit_pl.properties
src/main/resources/resources/logisim/strings/circuit/circuit_pt.properties
src/main/resources/resources/logisim/strings/circuit/circuit_ru.properties

same as #1018 but now targeted for the release version 3.6.0. It makes sense to intergrate this feature already in v3.6.0 as it simplifies some tasks in usage and correction.
* #1018

Feature: Tick frequency is preserved in .circ file (take 2) (to go into release 3.6.0)

---

src/main/java/com/cburch/logisim/fpga/designrulecheck/Netlist.java
src/main/java/com/cburch/logisim/fpga/gui/Reporter.java

Fixed endless loop in AddFataErrorFmt()

---

README.md

Fixed Github badges

---

src/main/java/com/cburch/logisim/analyze/gui/KarnaughMapPanel.java
src/main/java/com/cburch/logisim/file/XmlReader.java

Using assert is often considered bad practice as it could be turned on/off.

Removed use of `assert` from code.

---

src/main/java/com/cburch/logisim/fpga/hdlgenerator/WithSelectHDLGenerator.java
src/main/java/com/cburch/logisim/std/io/HexDigitHDLGeneratorFactory.java
src/main/java/com/cburch/logisim/util/LineBuffer.java
src/test/java/com/cburch/logisim/LineBufferTest.java

Improved LineBuffer by adding checks preventing adding positional arguments as global and vice versa.

Improved LineBuffer code

---

src/main/java/com/cburch/logisim/gui/start/Startup.java

As per discussion in #1019 
* Removed short CLO for "--clear-prefs"
* Fixed check for long CLO for test-fpga 
* #1019

CLOs cleanup

---

.github/workflows/nightly.yml

If merged, please leave #1073 opened.
* #1073

Triggers "nightly" after each merge in "develop"  too.

---

build.gradle.kts

Fixed MSI builder failing on unstable version strings.

---

src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74163.java

fixed bug in simulator for 74161 and 74163

---

.github/workflows/nightly.yml
build.gradle.kts

Corrected handling of ShadowJar filename for unstable versions

---

.github/workflows/nightly.yml
build.gradle.kts

* Removes redundant "$" character planted in shadowJar artifact uploader
* Modified `sourceJar` task to also use hyphenless version names for unstable builds.
* Rearranged Gradle script to have `extra.apply` executed before any task.

Removed redundant "$" character planted in shadowJar artifact uploader 

---

CHANGES.md
src/main/java/com/cburch/logisim/Main.java
src/main/java/com/cburch/logisim/prefs/AppPreferences.java
src/main/java/com/cburch/logisim/util/LocaleManager.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclComp.java
src/main/resources/resources/logisim/strings/util/util.properties
src/main/resources/resources/logisim/strings/util/util_de.properties
src/main/resources/resources/logisim/strings/util/util_el.properties
src/main/resources/resources/logisim/strings/util/util_es.properties
src/main/resources/resources/logisim/strings/util/util_fr.properties
src/main/resources/resources/logisim/strings/util/util_it.properties
src/main/resources/resources/logisim/strings/util/util_ja.properties
src/main/resources/resources/logisim/strings/util/util_nl.properties
src/main/resources/resources/logisim/strings/util/util_pl.properties
src/main/resources/resources/logisim/strings/util/util_pt.properties
src/main/resources/resources/logisim/strings/util/util_ru.properties

Fixes crash caused by invalid localized date format string as reported in #1095.
* #1095
* #1101

Invalid localized date format startup crash fix

---

build.gradle.kts
docs/developers.md

Followup to @MarcinOrlowski's review comments in #953. I wrote responses to the conversation there.

Cleanup after Update for Eclipse

---

src/main/java/com/cburch/logisim/LogisimVersion.java
src/test/java/com/cburch/logisim/LogisimVersionTest.java
src/test/java/com/cburch/logisim/TestBase.java

Reworked LogisimVersion class to also support "X.Y.Zsuffix" format (without "-" separator).
* BLOCKED_BY #1115

Reworked LogisimVersion class to also support "X.Y.Zsuffix" format

---

src/main/java/com/cburch/logisim/analyze/file/TruthtableTextFile.java

Fix for issue #1121

---

src/main/java/com/cburch/logisim/gui/main/SimulationTreeModel.java

Fixed wrong return value in getChildCount()

---

src/main/java/com/cburch/logisim/gui/main/Frame.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTop.java

Changed order of defalt frame title string elements to improve readability for unstable builds

Frame title string reformat

---

src/main/java/com/cburch/logisim/file/XmlCircuitReader.java
src/main/java/com/cburch/logisim/file/XmlReader.java

Fix subcircuits missing bug

---

src/main/java/com/cburch/logisim/analyze/gui/KarnaughMapPanel.java
src/test/java/com/cburch/logisim/fpga/hdlgenerator/HdlTest.java

Fixed karnaughmap incorrect RuntimeException.

---

src/main/java/com/cburch/draw/model/Drawing.java
src/main/java/com/cburch/logisim/circuit/CircuitAttributes.java
src/main/java/com/cburch/logisim/circuit/CircuitLocker.java
src/main/java/com/cburch/logisim/circuit/appear/CircuitAppearance.java
src/main/java/com/cburch/logisim/circuit/appear/CircuitCustomAppearance.java
src/main/java/com/cburch/logisim/file/LogisimFileActions.java
src/main/java/com/cburch/logisim/std/wiring/PinAttributes.java

This PR addresses #1272  and #1280

Fixes custom apearance merge bug and pin move bug

---

src/main/java/com/cburch/logisim/std/gates/Buffer.java

fixes #1249

---

src/main/java/com/cburch/logisim/circuit/ReplacementMap.java
src/main/java/com/cburch/logisim/circuit/Simulator.java
src/main/java/com/cburch/logisim/circuit/SplitterDistributeItem.java
src/main/java/com/cburch/logisim/circuit/WireBundle.java
src/main/java/com/cburch/logisim/data/Direction.java
src/main/java/com/cburch/logisim/gui/appear/AppearanceEditPopup.java
src/main/java/com/cburch/logisim/gui/chrono/PopupMenu.java
src/main/java/com/cburch/logisim/std/io/RgbLed.java
src/main/java/com/cburch/logisim/tools/LibraryTools.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlEntity.java

I addressed every issue in #560 except for:
- `pos++;` vs `++pos;`
- the ones regarding the localization's
- the two regarding Gradle ([1](https://github.com/logisim-evolution/logisim-evolution/pull/560#discussion_r631935194) and [2](https://github.com/logisim-evolution/logisim-evolution/pull/560#discussion_r631935292))
- the three regarding [KeyboardData.java](https://github.com/zdimension/logisim-evolution/blob/develop/src/main/java/com/cburch/logisim/std/io/KeyboardData.java) ([1](https://github.com/logisim-evolution/logisim-evolution/pull/560#discussion_r630004760), [2](https://github.com/logisim-evolution/logisim-evolution/pull/560#discussion_r630005480), [3](https://github.com/logisim-evolution/logisim-evolution/pull/560#discussion_r630006138))

Address issues found in code review of PR #560 (issue #564)

---

.github/workflows/build.yml
build.gradle.kts

This PR adds a SonarCloud analysis to the standard build workflow.

SonarCloud integration in CI

---

src/main/java/com/cburch/logisim/fpga/hdlgenerator/Hdl.java
src/main/java/com/cburch/logisim/std/wiring/BitExtenderHdlGeneratorFactory.java

Fixes bug reported in #1309 (use of bitextender makes synthesis stop working)

---

src/main/java/com/cburch/logisim/vhdl/base/HdlModel.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlContent.java
src/main/java/com/cburch/logisim/vhdl/gui/HdlContentView.java

closes #1308 
New function that does not validate the code which is called when necessary

No validation of VHDL code while editing it

---

src/main/java/com/cburch/logisim/vhdl/base/VhdlContent.java

as requested in #1327 ( https://github.com/logisim-evolution/logisim-evolution/pull/1327#discussion_r769903213 )

setContent function now calls setContentNoValidation

---

src/main/java/com/cburch/logisim/circuit/SplitterAttributes.java
src/main/java/com/cburch/logisim/data/AbstractAttributeSet.java
src/main/java/com/cburch/logisim/data/AttributeSet.java
src/main/java/com/cburch/logisim/gui/main/AttrTableComponentModel.java
src/main/java/com/cburch/logisim/gui/main/AttrTableSelectionModel.java
src/main/java/com/cburch/logisim/std/memory/CounterAttributes.java
src/main/java/com/cburch/logisim/std/wiring/Constant.java

This PR closes #1322. It also fixes the attribute undo problem described in #1337.

Fix Max update in Counter and problems with undo when extra attributes are changed

---

src/main/java/com/cburch/logisim/gui/main/Canvas.java
src/main/java/com/cburch/logisim/tools/PokeTool.java

scroll workaround for #1368

---

src/main/resources/resources/logisim/default.templ

Feature request for #1262 
Implemented panning on middle mouse button

(#1262) Added middle mouse button panning

---

src/main/java/com/cburch/logisim/fpga/data/FpgaIoInformationContainer.java
src/main/java/com/cburch/logisim/fpga/download/DownloadBase.java

Cloning was keeping old map information of the previous circuit causing some quite bizar effects when changing the circuit.

Fixes mapping bug reported in #1403.

---

src/main/java/com/cburch/logisim/std/ttl/DisplayDecoder.java
src/main/java/com/cburch/logisim/std/ttl/Ttl7447HdlGenerator.java

Edit the output value of the decoder to match the datasheet
Fix #1385
[Datasheet](https://www.ti.com/lit/ds/symlink/sn74ls47.pdf)
* #1385

Invert the output of the DisplayDecoder

---

CHANGES.md
src/main/java/com/cburch/logisim/gui/main/KeyboardToolSelection.java

fix CTRL+0 for toolbar [#1416]

---

src/main/java/com/cburch/logisim/std/ttl/Ttl74139.java

A partial fix on issue #1334 
Negates the output of 74139

Bugfix 1334 (only 74139)

---

CHANGES.md
src/main/java/com/cburch/logisim/std/ttl/Ttl7436.java
src/main/resources/resources/logisim/strings/std/std.properties

Fix TTL 7436 pin arrangement

---

src/main/java/com/cburch/logisim/util/LineBuffer.java

PR for [this](https://github.com/logisim-evolution/logisim-evolution/pull/1459#discussion_r927834561)  requested change.

LineBuffer var rename

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

This PR updates gradle to the latest version and also updates the dependencies to their latest versions.

Update gradle and dependencies

---

README.md

Feel free to re-target this PR to rc3.0.0 branch if that'd be better.

Corrected 'nightly builds' chapter in docs

---

.github/workflows/nightly.yml
README.md

Or maybe this should go against `master`?

Corrected nightly builder

---

src/main/java/com/cburch/logisim/gui/menu/MenuSimulate.java
src/main/java/com/cburch/logisim/proj/Dependencies.java
src/main/java/com/cburch/logisim/soc/bus/SocBus.java
src/main/java/com/cburch/logisim/soc/bus/SocBusAttributes.java
src/main/java/com/cburch/logisim/vhdl/base/HdlContent.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlContent.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlEntity.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlEntityAttributes.java
src/main/java/com/cburch/logisim/vhdl/base/VhdlParser.java
src/main/java/com/cburch/logisim/vhdl/file/HdlFile.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTclBinder.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorTop.java
src/main/java/com/cburch/logisim/vhdl/sim/VhdlSimulatorVhdlTop.java

* refactored to use instanceof + cast syntax
* Replaced explicit declarations with final var
* Code cleanup
* Replaced use of boxed Boolean with boolean primitive
* Corrected boxed vars comparison code

Code cleanup

---

CHANGES.md
src/main/java/com/cburch/logisim/analyze/data/CoverColor.java

Fixed bug in kmap map colors (issue #1558)

---

docs/developers.md
docs/style.md

@davidhutchens can you please take a look?

Corrected and updated developer docs

---

build.gradle.kts

This PR fixes the gradle check task.¨
Fixes issue #1620 
* #1620

Fixes "gradlew not working" (issue #1620)

---

.github/workflows/nightly.yml
README.md

Fix package names for Mac and Windows packages

---

.github/workflows/build.yml
.github/workflows/checkstyle.yml
.github/workflows/markdown.yml
.github/workflows/nightly.yml
.github/workflows/translations.yml

This PR should update the deprecated actions in nightly as noted in #1590.

Update deprecated github workflow actions

---

src/main/java/com/cburch/logisim/std/ttl/Ttl747266.java

TTL747266 fix IEC internal view

---

CHANGES.md
src/main/java/com/cburch/logisim/std/ttl/Ttl74151.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74153.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74181.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74182.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74299.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74381.java
src/main/java/com/cburch/logisim/std/ttl/Ttl74541.java

Fixed copyright statements of added files and updated changes.md with the new TTL models

---

src/main/java/com/cburch/logisim/circuit/Propagator.java
src/main/java/com/cburch/logisim/gui/opts/SimulateOptions.java

Currently this is fixed at 1000, we can use the value from the options menu

Fix Iterations until oscillation

---

CITATION.cff

Add `CITATION.cff`.
I did this to my best knowledge.
Feel free to give feedback.
As requested by @MarcinOrlowski in #1656.

Add citation file (into develop branch)

---

support/jpackage/linux/file.jpackage
support/jpackage/macos/file.jpackage
support/jpackage/windows/file.jpackage

Change the mime-type to be consistent between Flatpak and jpackage.
https://github.com/logisim-evolution/logisim-evolution/blob/a8e3c096bbdad57975bbe4e8731c1e6cf5d09023/support/Flatpak/com.github.reds.LogisimEvolution.xml#L1-L7
This also helps with the issues:
* #1471
* #1752

Change mime-type in jpackage

---

src/main/java/com/cburch/logisim/soc/nios2/Nios2ProgramControlInstructions.java

Corrected a bug in the nios assembler where the target address was incorrectly calculated.

Fixed the br nios command reported in #1758

---

src/main/java/com/cburch/logisim/analyze/gui/KarnaughMapPanel.java
src/main/java/com/cburch/logisim/util/AlphanumComparator.java
src/test/java/com/cburch/logisim/util/AlphanumComparatorTest.java

This converts a main method as discussed in #1415 by converting it to a test.
It also fixes a null pointer exception I ran into while looking at another main method. The fix is consistent with other close by null pointer tests. This one was somehow originally missed.

Convert a main method to a junit test

---

src/main/java/com/cburch/logisim/circuit/appear/CircuitAppearance.java
src/main/java/com/cburch/logisim/file/XmlCircuitReader.java
src/main/java/com/cburch/logisim/file/XmlWriter.java

https://github.com/kevinawalsh/logisim-evolution/issues/92

Cherry picked a bugfix by Kevin Walsh for the custom circuit appearance

---

src/main/java/com/cburch/logisim/circuit/Propagator.java
src/main/java/com/cburch/logisim/circuit/Simulator.java
src/main/java/com/cburch/logisim/gui/log/LogFrame.java
src/main/java/com/cburch/logisim/gui/menu/MenuSimulate.java

https://github.com/kevinawalsh/logisim-evolution/commit/cfe2da606a3282078bee77cb2f64ab03274c7020

Cherry picking: Merged simulator update of Kevin Walsch

---

src/main/java/com/cburch/logisim/std/memory/RamAppearance.java

Fix the small problem in the appearance of classic-Logisim RAMs

Fix the point of issue #1772  appearance of classic-Logisim RAMs

---

src/main/resources/resources/logisim/strings/gui/gui_zh.properties

This is a small update that add translation for hotkeyoptions strings. Hope it can catch up to the v3.9.0 release.

Chinese localization: Translate hotkeyoptions strings

---

src/main/java/com/cburch/logisim/std/wiring/PowerOnReset.java
src/main/resources/resources/logisim/strings/gui/gui_fr.properties
src/main/resources/resources/logisim/strings/std/std.properties
src/main/resources/resources/logisim/strings/std/std_de.properties
src/main/resources/resources/logisim/strings/std/std_el.properties
src/main/resources/resources/logisim/strings/std/std_es.properties
src/main/resources/resources/logisim/strings/std/std_fr.properties
src/main/resources/resources/logisim/strings/std/std_it.properties
src/main/resources/resources/logisim/strings/std/std_ja.properties
src/main/resources/resources/logisim/strings/std/std_nl.properties
src/main/resources/resources/logisim/strings/std/std_pl.properties
src/main/resources/resources/logisim/strings/std/std_pt.properties
src/main/resources/resources/logisim/strings/std/std_ru.properties
src/main/resources/resources/logisim/strings/std/std_zh.properties

improved Power On Reset and additional French translation

Improved Power On Reset  Issue #1808

---

src/main/java/com/cburch/logisim/gui/generic/OptionPane.java
src/main/java/com/cburch/logisim/gui/start/About.java
src/main/resources/resources/logisim/strings/gui/gui.properties
src/main/resources/resources/logisim/strings/gui/gui_de.properties
src/main/resources/resources/logisim/strings/gui/gui_el.properties
src/main/resources/resources/logisim/strings/gui/gui_es.properties
src/main/resources/resources/logisim/strings/gui/gui_fr.properties
src/main/resources/resources/logisim/strings/gui/gui_it.properties
src/main/resources/resources/logisim/strings/gui/gui_ja.properties
src/main/resources/resources/logisim/strings/gui/gui_nl.properties
src/main/resources/resources/logisim/strings/gui/gui_pl.properties
src/main/resources/resources/logisim/strings/gui/gui_pt.properties
src/main/resources/resources/logisim/strings/gui/gui_ru.properties
src/main/resources/resources/logisim/strings/gui/gui_zh.properties

Refactored About dialog and added option to copy all technical details to the clipboard so in case of bug report etc we can simply ask user to go there and get all the info we need:
```
Product: Logisim-evolution v3.9.0dev
Runs on: Java HotSpot(TM) 64-Bit Server VM v16.0.1
Compiled: 2023-09-10T18:29:11+0200
Build ID: help-about-copy/1fd67a33
Built on: Java HotSpot(TM) 64-Bit Server VM v16.0.1
```
with single click:

Adds option to easily get all the build details

---

src/main/java/com/cburch/logisim/gui/log/ClockSource.java
src/main/java/com/cburch/logisim/gui/log/ComponentSelector.java
src/main/java/com/cburch/logisim/gui/log/LogThread.java
src/main/java/com/cburch/logisim/gui/log/Model.java
src/main/java/com/cburch/logisim/gui/log/OptionsPanel.java
src/main/java/com/cburch/logisim/gui/log/SignalInfo.java
src/main/java/com/cburch/logisim/gui/log/ValueTable.java

The only non "final var" refactoring is `circuitChanged()` in `src/main/java/com/cburch/logisim/gui/log/ComponentSelector.java` but that's squashes conditionals into one branch.

Another set of "final var" refactorings

---

src/main/java/com/cburch/logisim/gui/main/CanvasPainter.java
src/main/java/com/cburch/logisim/gui/main/LayoutToolbarModel.java
src/main/java/com/cburch/logisim/gui/main/Print.java
src/main/java/com/cburch/logisim/gui/main/SelectionActions.java
src/main/java/com/cburch/logisim/gui/main/SelectionAttributes.java
src/main/java/com/cburch/logisim/gui/main/SelectionBase.java
src/main/java/com/cburch/logisim/gui/main/SelectionSave.java
src/main/java/com/cburch/logisim/gui/main/SimulationExplorer.java
src/main/java/com/cburch/logisim/gui/main/SimulationTreeCircuitNode.java
src/main/java/com/cburch/logisim/gui/main/SimulationTreeModel.java
src/main/java/com/cburch/logisim/gui/main/SimulationTreeRenderer.java
src/main/java/com/cburch/logisim/gui/main/SimulationTreeTopNode.java
src/main/java/com/cburch/logisim/gui/main/StatisticsDialog.java
src/main/java/com/cburch/logisim/gui/main/ToolAttributeAction.java
src/main/java/com/cburch/logisim/gui/main/Toolbox.java
src/main/java/com/cburch/logisim/gui/main/ToolboxManip.java

Replaced explicit variable types with var/final var. Small code cleanup + change to `fireNodeChanged()` in src/main/java/com/cburch/logisim/gui/main/SimulationTreeModel.java and no other logic changes

Replaced explicit variable types with var/final var

---

src/main/java/com/cburch/logisim/prefs/AbstractPrefMonitor.java
src/main/java/com/cburch/logisim/prefs/AppPreferences.java
src/main/java/com/cburch/logisim/prefs/ConvertEvent.java
src/main/java/com/cburch/logisim/prefs/FpgaBoards.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorBoolean.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorBooleanConvert.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorDouble.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorInt.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorKeyStroke.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorString.java
src/main/java/com/cburch/logisim/prefs/PrefMonitorStringOpts.java
src/main/java/com/cburch/logisim/prefs/RecentProjects.java
src/main/java/com/cburch/logisim/prefs/Template.java
src/main/java/com/cburch/logisim/util/LocaleListener.java

Scope of the PR (each type of change in separate commit)
* Replaced empty string comparison with isEmpty() 
* Added code documentation
* "final var" refactoring

Added code documentation + final var cleanup

---

src/main/java/com/cburch/logisim/fpga/gui/FpgaIoInformationSettingsDialog.java

Fixed window close button on some FPGA windows

---

src/main/java/com/cburch/logisim/std/plexers/DecoderHdlGeneratorFactory.java

Fix decoders without enable generating an error when synthesizing generated HDL

---

src/main/resources/doc/de/html/style.css
src/main/resources/doc/el/html/style.css
src/main/resources/doc/en/html/style.css
src/main/resources/doc/es/html/style.css
src/main/resources/doc/fr/html/style.css
src/main/resources/doc/it/html/style.css
src/main/resources/doc/nl/html/style.css
src/main/resources/doc/pt/html/style.css
src/main/resources/doc/ru/html/style.css
src/main/resources/doc/zh/html/style.css

Fixed the background not changing with the selected theme as described in issue #1675.

Fix docs dark theme

---

CHANGES.md
README.md

I used grep to find all 16s in docs but missed the README. Thank you for catching it, @maehne.

Update README to Java 21.

---

src/main/java/com/cburch/logisim/gui/main/SelectionActions.java

This PR closes issue #1960. I have described the solution in detail in that issue.

Make redo not be dependent on current selection in SelectionActions.

---

README.md
docs/developers.md

This PR updates the documents to reflect the deletion of the master branch by removing all references to it.
It also better describes how to find the latest Nightly build since we switched to the main branch.

Update documents regarding master branch and nightly builds.

---

CITATION.cff

typo: Update version specific info in CITATION.cff

---

src/main/resources/resources/logisim/strings/gui/gui_de.properties

fix switched german translation in GUI

---

build.gradle.kts

Fix deprecation related to use of `project` in build noted in Issue #2144.

Fix project.name warning in gradle.

---

src/main/java/com/cburch/logisim/circuit/appear/DefaultAppearance.java
src/main/java/com/cburch/logisim/circuit/appear/DefaultEvolutionAppearance.java

1) Due to the re-ordering of the possible clock pins, backward
compatibility was broken
2) Due to the re-ordering of the possible clock pins, the HDL generation
was broken.

This PR fixes two "bugs" introduced by #2158

---

src/main/java/com/cburch/logisim/gui/generic/RegTabContent.java

@davidhutchens I just saw your commit and had this to add. The simulation thread should never be blocked by the rendering thread. In this case that means using a `CopyOnWriteArrayList` where writes become a little more expensive, but concurrency becomes trivial. Writes rarely happen, so this is the perfect collection for this case. Note that even though writes rarely happen, the blocking was still a problem, because the label text updates used the same locks, so the rendering thread did block the simulation thread on every frame. I did notice a couple percent performance improvement with this fix.

RegTabContent: don't use blocking synchronisation

---

build.gradle.kts

This PR addresses issue #2227. I added a task to create a file containing the needed Java modules using jdeps. I also added a function that appends the --add-module option to the desired parameter list.
This should be tested on Linux and Windows.

Fix --add-module option in build to use jdeps.

---

gradle/wrapper/gradle-wrapper.properties

Update Gradle to recommended version 8.14.1.

Update Gradle to version 8.14.1

---

build.gradle.kts

This PR updates our checkstyle version. I hope it fixes the recently reported Security issues.

Update checkstyle version.

---

CHANGES.md
src/main/java/com/cburch/logisim/std/memory/RamHdlGeneratorFactory.java

Solves the issues #1996 and #1598

Added VHDL and Verilog generator for RAM-components that use line-enables, adressing #1996 and #1598

---

CHANGES.md
src/main/java/com/cburch/logisim/std/memory/RamHdlGeneratorFactory.java

Added VHDL generation for RAMs with byte enables for write-after-read and asynchronous read.
Added Verilog generation for RAMs with byte enables.

Updated VHDL generator for RAM's with byte enables and added the Verilog generator.

---

build.gradle.kts
gradle/wrapper/gradle-wrapper.properties

Update Gradle to version 8.14.2 and its Shadow plug-in to 8.3.7

Update Gradle to version 8.14.2 and its Shadow plug-in to 8.3.7

---

build.gradle.kts

This PR updates Shadow to 9.0.0 and Checkstyles to 11.0.0.

Update Shadow to 9.0.0 and Checkstyle to 11.0.0.
