logisim-evolution/logisim-evolution

src/com/bfh/logisim/hdlgenerator/HDLColorRenderer.java, src/com/cburch/logisim/circuit/Wire.java
Issues were arising where changing the bits and fanout on a splitter connected to an input would throw NullPointerExceptions. The second commit guards against these changes, the first commit is merely style changes to not have the dots overlapping when close with a wire bus.
=> Splitter fixes, null pointer exception

src/com/cburch/logisim/Main.java
The scaling_resolution_wip branch @ 4c96148 fails to build due to unknown class ```com.cburch.logisim.gui.scale.ScaledOptionPane```.
=> Fix compilation error due to unknown class ScaledOptionPane

.gitignore
/.idea is IDE settings, .iml files are autogenerated on importing to intellij despite not being used in the ant build process. /out is where intellij sticks the class files if you ignore the readme's instructions and just try to build from Build>Build Project (guilty).
=> Added intellij related entries to .gitignore

build.xml, package/linux/postrm
Without this fix, the logisim-evolution command line tool in /usr/bin is only deleted when purging the Debian package. In consequence, upgrading the Debian package failed.
The PR also updates the Logisim-evolution package version to 2.14.1 in the build.xml file. Keeping the version information in two locations is unsatisfying, as they can easily get out-of-sync. Maybe, someone has an idea how to centralize this information to a unique location. Also, you may consider to update the copyright year, it is still set to 2014...
=> Fix the DEB postrm script to delete the logisim-evolution command line tool

src/com/cburch/logisim/gui/log/ComponentSelector.java, src/com/cburch/logisim/gui/main/SimulationTreeNode.java
I am not sure why compiling the master branch on my machine throws these errors, it could be related to my environment (JDK 8u144 on macOS High Sierra). I attached the build output below. This commit fixes the aforementioned errors. Maybe I'm missing something else, any hint would be appreciated.
```
compile:
[javac] Compiling 791 source files to /Users/nicolas/development/logisim-evolution/bin
[javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
[javac] /Users/nicolas/development/logisim-evolution/src/com/cburch/logisim/gui/main/SimulationTreeNode.java:40: error: children() in SimulationTreeNode cannot implement children() in TreeNode
[javac] 	public abstract Enumeration<?> children();
[javac] 	                               ^
[javac]   return type …
```
=> Use "extends TreeNode" to fix compilaton with javac 1.8.0_144

build.xml, package/macosx/Info.plist
See the commit messages for details. The modified ```build.xml``` works for me with JDK 9.0.1 on macOS High Sierra. Testing on other platforms is needed.
The addition of ```Info.plist``` to fix issue #142 introduces unfortunately yet a third place in which the version of Logisim-evolution is mentioned, which has to be kept in sync for the displayed version numbers to stay consistent. It would be good to somehow update the version number in the Java sources and Info.plist through some ant task.
=> Fix issues #135 and #142

src/com/cburch/logisim/std/arith/MultiplierHDLGeneratorFactory.java
Fixes the signed 32-bit multiplier carry with a pseudo-unsigned long cast if a 32-bit multiplier is used.
=> Fix issue #129

src/com/cburch/logisim/std/arith/Multiplier.java
It currently does not compile without it.
```
compile:
[mkdir] Created dir: /Users/leijurv/Downloads/logisim-evolution/bin
[javac] Compiling 791 source files to /Users/leijurv/Downloads/logisim-evolution/bin
[javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
[javac] /Users/leijurv/Downloads/logisim-evolution/src/com/cburch/logisim/std/arith/Multiplier.java:142: error: cannot find symbol
[javac] 		setAttributes(new Attribute[] { StdAttr.WIDTH },
[javac] 		                                ^
[javac]   symbol:   variable StdAttr
[javac]   location: class Multiplier
[javac] /Users/leijurv/Downloads/logisim-evolution/src/com/cburch/logisim/std/arith/Multiplier.java:144: error: cannot find symbol
[javac] 		setKeyConfigurator(new …
```
=> Added missing import

logisim_evolution_version.xml, src/main/java/com/cburch/logisim/LogisimVersion.java, src/main/java/com/cburch/logisim/Main.java, src/main/java/com/cburch/logisim/file/XmlCircuitReader.java, src/main/java/com/cburch/logisim/file/XmlReader.java, src/main/java/com/cburch/logisim/gui/start/Startup.java
We are still bounded to heig-vd servers for the auto-update.
The .xml containing the logisim version and the .jar to be downloaded are on reds-data.heig-vd.ch
This PR offers to have everything on github.
The jar is taken from github's releases folder and the logisim_evolution_version.xml is on the project root.
Note:
This PR remove support for auto-update of the tracked version.
Note 2:
To be able to test this PR, it needs to have the logisim_evolution_version.xml on github. (So it would require to merge the request to be able to test it...!)
So for test purpose, I set the UPDATE_URL (in Main.java) to target my own github repo. 
If you accept the PR, I will re-set this URL to this reds-heig/logisim-evolution repository
=> Change auto-update repository source

build.gradle.kts
This is a minor change in the Info.plist file for Macs that adds one key that maps the document icon to the Logisim-evolution icon. The result is that all .circ files on the Mac will have the app icon rather than the generic document icon. You may need to log out and back in or even reboot after opening the app with the Finder to get the Finder to start using the icon, since we are not using an app installer.
=> Use app icon for document icon on Mac

src/main/java/com/cburch/logisim/data/Value.java, src/main/java/com/cburch/logisim/gui/prefs/LayoutOptions.java, src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/resources/resources/logisim/en/gui.properties
I updated the correct branch with my original changes. This patch adds a colorblind mode to preferences -> layout that toggles a regular color scheme and a red/green colorblind color scheme.
=> Colorblind mode for red/green colorblind individuals

src/main/java/com/cburch/logisim/gui/log/LogFrame.java
Updated LogFrame.java to implement KeyListener.
Added the key listener to the LogFrame to the JPanels, F2 key now ticks the clock when in the "Table" window of the Chronogram.
=> F2 chrono fix

src/main/java/com/cburch/logisim/data/Value.java
The crash was caused by access to unitialized WIDTH_ERROR_COLOR.
Introduce static initializer, even if the value may be overridden later.
=> Fix crash when using -tty option. See reds-heig#342

src/main/java/com/cburch/logisim/std/memory/Mem.java, src/main/java/com/cburch/logisim/std/memory/RamAppearance.java, src/main/resources/resources/logisim/de/std.properties, src/main/resources/resources/logisim/el/std.properties, src/main/resources/resources/logisim/en/std.properties, src/main/resources/resources/logisim/es/std.properties, src/main/resources/resources/logisim/fr/std.properties, src/main/resources/resources/logisim/it/std.properties, src/main/resources/resources/logisim/nl/std.properties, src/main/resources/resources/logisim/pt/std.properties, src/main/resources/resources/logisim/ru/std.properties
Add octo line size to be able to simulate 64-bit byte-addressed memory.
=> add octo line size to memory

src/main/java/com/cburch/logisim/std/memory/Mem.java, src/main/java/com/cburch/logisim/std/memory/MemState.java, src/main/java/com/cburch/logisim/std/memory/Ram.java, src/main/java/com/cburch/logisim/std/memory/RamAttributes.java, src/main/java/com/cburch/logisim/std/memory/Rom.java, src/main/java/com/cburch/logisim/std/memory/RomAttributes.java, src/main/resources/resources/logisim/en/std.properties
I don't know if "Use line enables" option is here to stay, but currently under this option, any unaligned access will set all the outputs as errors.
In real hardware, you might need some extra read/write ports and shift and mask or something, but this attribute can simplify the circuit by assuming all of that is conveniently implemented within the RAM/ROM block.
=> attribute for allowing unaligned multi-line ram/rom accesses

src/main/java/com/cburch/logisim/std/memory/MemContents.java
Looking at the logs, it looks like this bug (?) came back again during a merge. I'm not sure what this check is doing, but I was seeing in the log:
> "memory width mismatch: src is 24 bits wide, dest is 24 bits wide"
=> fix load memory contents from file

src/main/java/com/cburch/logisim/gui/menu/MenuEdit.java
This PR fixes the accelerator key for Redo to be cmd-shift-Z as requested in #386. The conflict noted there with Reset Simulator should exist on all platforms and this PR should fix all of them to the customary cmd-shift-Z or ctrl-shift-Z.
=> Fix redo accelerator key to be cmd-shift-Z

src/main/java/com/cburch/logisim/gui/hex/HexFile.java
With support for value sizes up to 64-bits, casts of parsed numbers to integers should be removed.
=> Fix loading hex for words larger than 32 bits

src/main/java/com/cburch/logisim/circuit/Simulator.java, src/main/java/com/cburch/logisim/circuit/SimulatorTicker.java, src/main/java/com/cburch/logisim/comp/ComponentDrawContext.java, src/main/java/com/cburch/logisim/std/memory/AbstractFlipFlop.java, src/main/java/com/cburch/logisim/std/memory/Counter.java, src/main/java/com/cburch/logisim/std/memory/RamAppearance.java, src/main/java/com/cburch/logisim/std/memory/Register.java, src/main/java/com/cburch/logisim/std/memory/ShiftRegister.java, src/main/java/com/cburch/logisim/util/GraphicsUtil.java
Using System.currentTimeMillis() made clock ticks like 2kHz impossible
due to creating a 1ms wait, which meant that 1kHz and 2kHz options were
essentially the same.
Some of the memory components drew things with several lines instead of polylines, for essentially the same thing. I also modified the clock to use a polyline instead of two lines, as it looks better.
The 1/0 in the flip flops wasn't centered, so that is also fixed.
=> Use more accurate clock and unified memory components design

src/main/java/com/cburch/logisim/circuit/RadixOption.java, src/main/java/com/cburch/logisim/data/Value.java, src/main/java/com/cburch/logisim/std/wiring/Constant.java, src/main/java/com/cburch/logisim/std/wiring/ConstantConfigurator.java
Even with the recent decimal number fix, LogiSim still displays some bit widths incorrectly (see figures below). This fixes the following problems:
- Probe for 1..3-bit unsigned numbers is a lot wider than necessary.
- Probe for 64-bit unsigned numbers is a bit too narrow.
- Probe incorrectly displays 32..63-bit unsigned values.
- Constant incorrectly displays 33..64-bit values.
Wrong (red dots mark the problematic spots):
Right (after fix):
=> Fix display of unsigned values in probe/constant

src/main/resources/resources/logisim/pl/util.properties
The wrong dateFormat caused an exception at start up when a polish
locale is active.
This fixes issue #477.
=> Fix dateFormat in polish localization

src/main/java/com/cburch/logisim/circuit/CircuitState.java
If one tries to reset the simulation while a buzzer is active, the stream is not properly closed and the whole program becomes unuseable, because since the buzzer initializes a new Data object, it's impossible to turn off the tone without closing Logisim completely. This fixes the problem by preventively calling StopBuzzerSound on all buzzers when the simulation is reset.
=> Fix buzzer not resetting on simulation reset

README.md, build.gradle.kts, support/jpackage/macos/Logisim-evolution-post-image.sh, support/jpackage/macos/file.jpackage
This PR changes the macos dmg and app names to start with uppercase L.
It also makes changes in support/jpackage/macos that should allow the build to work properly on case-sensitive mac file systems.
It should now be easy to test uppercase L on either Linux of Windows systems if desired by changing the --name parameter to appname.
I noticed in changing the name of the dmg in the README.md that it says to use at least OpenJDK 9. I updated that to 11.
=> Change macos app name to start with upper case L

src/main/java/com/cburch/logisim/analyze/model/TruthTable.java
When modifying Truth Table model, loop through the Truth Table rows by index, because the Table is modified inside the loop.
Using a `for (Row r : rows)` iterator throws a `java.util.ConcurrentModificationException`.
A loop by index was used in the original implementation, but was recently changed to an iterator in e1d7ce0f6bee88ed460ffcaa9e6ddcfacd1dcbd9.
Fixes #511
=> Loop Truth Table by index because modified in loop

src/main/java/com/cburch/logisim/std/io/extra/Slider.java
The Slider value attribute is used in class `com.cburch.logisim.std.io.extra.Slider` as a 64 bit value, so must be initialized as a 64 bit value with type `java.lang.Long` instead of type `java.lang.Integer`, to avoid java casting exceptions.
Fixes #509
=> Initialize Slider value attribute to 64 bit zero value

src/main/java/com/cburch/logisim/data/TestVector.java, src/main/java/com/cburch/logisim/data/Value.java
Allow 64 bit width in Test Vector file header.
Removed unnecessary "too many bits" check whilst reading digits of Test Vector file values. This test does not work for 64 bits (`value >> 64` always returns the same 64 bit `value`). The test at the end of the loop after parsing all digits is already adequate for testing "too many bits".
Fixes #507
=> Allow 64 bit Test Vector file

src/main/java/com/cburch/logisim/data/TestVector.java
If a `java.lang.NumberFormatException` occurs when parsing a bit width from a test vector file, then display an error dialog with a message like _Test vector in "test2.txt" could not be parsed. Detail: Test Vector header format error: bad width: O[2.0]._
Fixes #502
=> Handle invalid bit width in test vector file

src/main/java/com/cburch/logisim/analyze/data/ExpressionRenderData.java
Removed special logic for converting parentheses and dot characters to underscores before calculating width of expression text.
Java returns the correct widths for strings containing these characters, so no special logic is needed.
The only special case is spaces. Java will return the same width for "abc" and "abc ", so we do need to convert each space to an underscore, before calculating widths.
Attaching screenshots of expressions in #284 after my changes on Windows 10 and Ubuntu Linux, both with OpenJDK 11. I have no Mac for testing.
X = NOT A AND NOT B OR NOT A AND D OR NOT A AND C OR B AND C AND D
Y = (A OR B OR NOT C) AND (A OR NOT C OR NOT D) AND (A OR NOT B OR C OR D) AND (NOT A OR NOT B OR NOT D) AND (NOT A OR NOT B OR NOT C)
Fixes #284
=> Fixed alignment of inversion bars in Combinatorial Analysis Expressions

src/main/java/com/cburch/logisim/std/memory/Counter.java
Use 64-bit mask, not 32-bit mask, for determining "0" and "1" labels for Counter component pin display.
Fixes #527
=> Use 64-bit arithmetic for 0/1 pin display of 64-bit Counter

src/main/java/com/cburch/logisim/gui/hex/HexFile.java
If you paste a sequence of hex words into a 64 bit ROM using the hex editor in the current develop version, it only takes 32 bits worth (sign extended to the full 64 bits). This PR fixes this problem so the paste works correctly for all 64 bits.
=> Fixed hex paste to work with 64 bit

src/main/java/com/cburch/logisim/analyze/model/TruthTable.java
Thanks @simoc for diagnosing (again) the cause for issue #579! I reapplied your fix from commit 39c355 to `TruthTable::removeInput()`.
@zdimension: Feel free to suggest a better fix.
@BFH-ktt1: Might this warrant a hot fix release?
=> Loop again rows by index in TruthTable::removeInput()

.github/workflows/gradle.yml
Do CI runs with JDK 16 instead of JDK 15 in addition to JDK 11.
=> Do CI runs with JDK 16 instead of JDK 15

src/main/java/com/cburch/logisim/analyze/gui/KarnaughMapPanel.java, src/main/resources/resources/logisim/strings/analyze/analyze.properties, src/main/resources/resources/logisim/strings/analyze/analyze_de.properties, src/main/resources/resources/logisim/strings/analyze/analyze_el.properties, src/main/resources/resources/logisim/strings/analyze/analyze_es.properties, src/main/resources/resources/logisim/strings/analyze/analyze_fr.properties, src/main/resources/resources/logisim/strings/analyze/analyze_it.properties, src/main/resources/resources/logisim/strings/analyze/analyze_ja.properties, src/main/resources/resources/logisim/strings/analyze/analyze_nl.properties, src/main/resources/resources/logisim/strings/analyze/analyze_pt.properties, src/main/resources/resources/logisim/strings/analyze/analyze_ru.properties
If there is only one input to a Karnaugh Map, then display the message "Too few inputs for table" instead.
A Karnaugh Map only makes sense if there are at least two inputs.
I have added this message string to the `analyze.properties` files for some languages, but left the placeholder `# ==> karnaughTooFewInputsError =` for the languages for which I have no idea of the translation.
Fixes #578
=> Display "Too few inputs for table" if Karnaugh Map has only 1 input

src/main/java/com/cburch/logisim/comp/ComponentDrawContext.java, src/main/java/com/cburch/logisim/gui/prefs/LayoutOptions.java, src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/java/com/cburch/logisim/tools/AddTool.java, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties
Currently size of connection markers are too small and hard to see, especially when using i.e 4K monitors or zooming the circuit out. This PR adds configuration option (in `Preferences->Layout`) to set appearance of connection pin markers. Currently 4 sizes are available: "Small dot" (current appearance), "medium dot" (x1.5), "big dot" (x2) and "bigger dot" (x2.5), which looks as follow:
At zoom 100%:
At zoom 80%
=> Configurable connection pin markers

src/main/java/com/cburch/logisim/std/ttl/Ttl74161.java
Makes tooltips of 74161's pins to be more descriptive and also include naming used by NXP or Motorola, not just TI. 
Rationale: this came after discussion with one of my students, who complained that his life, as newbie in the field, would definitely be simpler if he could focus more on the assignment, instead of deciphering pin meanings. While this may looks like silly complaint for pros, I took a closer look how 74161 is represented here. It seems that current pins are labeled as it is present in i.e. Texas Instruments datasheet. However, if you get i.e. HC version of the IC from other vendors, they may not use the same names which apparently is a problem for newbies.  For example NXP ([sheet](https://pdf1.alldatasheet.com/datasheet-pdf/view/15545/PHILIPS/74HC161.html)) or Motorola …
=> Made pins' tooltips more descriptive for 74161

src/main/java/com/cburch/gray/Components.java, src/main/java/com/cburch/logisim/file/LoadedLibrary.java, src/main/java/com/cburch/logisim/file/LogisimFile.java, src/main/java/com/cburch/logisim/file/XmlReader.java, src/main/java/com/cburch/logisim/fpga/library/BFHPraktika.java, src/main/java/com/cburch/logisim/gui/start/Startup.java, src/main/java/com/cburch/logisim/soc/Soc.java, src/main/java/com/cburch/logisim/std/Builtin.java, src/main/java/com/cburch/logisim/std/arith/Arithmetic.java, src/main/java/com/cburch/logisim/std/base/Base.java, src/main/java/com/cburch/logisim/std/gates/Gates.java, src/main/java/com/cburch/logisim/std/hdl/Hdl.java, src/main/java/com/cburch/logisim/std/io/Io.java, src/main/java/com/cburch/logisim/std/io/extra/ITA_IO.java, src/main/java/com/cburch/logisim/std/memory/Memory.java, src/main/java/com/cburch/logisim/std/plexers/Plexers.java, src/main/java/com/cburch/logisim/std/tcl/Tcl.java, src/main/java/com/cburch/logisim/std/ttl/TTL.java, src/main/java/com/cburch/logisim/std/wiring/Wiring.java, src/main/java/com/cburch/logisim/tools/AddTool.java, src/main/java/com/cburch/logisim/tools/Library.java, src/main/java/com/cburch/logisim/tools/LibraryTools.java
Changes:
* Removes redundant `removeLibrary()` implementations
* Removes empty constructors
* Introduces library static _ID field and reworks generic getName() to look for it to reduce redundant code and remove library references via library name hardcoded in referring code.
=> Cleanup of component libraries

src/main/resources/resources/logisim/strings/soc/soc.properties, src/main/resources/resources/logisim/strings/soc/soc_de.properties, src/main/resources/resources/logisim/strings/soc/soc_es.properties, src/main/resources/resources/logisim/strings/soc/soc_fr.properties, src/main/resources/resources/logisim/strings/soc/soc_it.properties, src/main/resources/resources/logisim/strings/soc/soc_ja.properties, src/main/resources/resources/logisim/strings/soc/soc_nl.properties, src/main/resources/resources/logisim/strings/soc/soc_pt.properties, src/main/resources/resources/logisim/strings/soc/soc_ru.properties, src/main/resources/resources/logisim/strings/std/std.properties, src/main/resources/resources/logisim/strings/std/std_de.properties, src/main/resources/resources/logisim/strings/std/std_it.properties, src/main/resources/resources/logisim/strings/std/std_ja.properties, src/main/resources/resources/logisim/strings/std/std_nl.properties, src/main/resources/resources/logisim/strings/std/std_pt.properties
Library labels cleanup:
Changed 'RGBLED' label to 'RGB LED'
Ensured 'DIP' in 'DIP Switch' label is all upper-cased
Shortened "System on Chip Components" label by dropping "Components" from it.
Renamed "Input/Output-Extra" to "Input/Output Extra"
Ensured "System on a chip" abbrev. is spelled "SoC"
Ensured JTAG and UART proper spelling
Corrected full form of SoC to "System On a Chip"
=> Small library labels cleanup

src/main/java/com/cburch/logisim/gui/generic/ZoomControl.java, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties
Removed ZoomText label from ZoomControl panel as it just occupied screen state adding no additional long term value justifying its permanent presence.
=> Removed ZoomText label

src/main/java/com/cburch/logisim/analyze/file/TruthtableTextFile.java, src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java, src/main/java/com/cburch/logisim/fpga/data/MappableResourcesContainer.java, src/main/java/com/cburch/logisim/gui/test/TestThread.java, src/main/java/com/cburch/logisim/soc/util/AssemblerInfo.java
* Replaced looped switch()'s case termination to use "break", not "continue"
* Removed unnecessary "continue"s
=> Code sweeping (looped switches)

README.md
I don't know if Documentation is the right section, but other links seemed similar.
Currently, it's mostly the circuit files. But I'm in the process of adding some documentation: https://mkayaalp.net/computer-organization-logisim.
=> Add link of circuit repo to README.md

src/main/java/com/cburch/logisim/gui/hex/HexFile.java
The reason the redo of my fix failed my tests is that a line was changed. That line was supposed to parse a base 10 unsigned count from the format "count*hexvalue". This PR returns it to the original submission.
This PR solves issue #674.
=> Finish reapplication of code to fix reading of memory values from .circ files

README.md, build.gradle.kts, checkstyle/README.md, checkstyle/logisim.xml
This adds more info on how to use CheckStyle (either with Gradle or InteliJ). I also tweaked style a bit, disabling two "most popular" complains CheckStyle on my first cleanup of "util/" content, be it "MissingJavadocMethod" and "NeedBraces" as there's lot of one-liners without the curly braces. There're other complains too, but I will post more in #698 about that.
=> Added CheckStyle docs + corrected config

.github/workflows/markdown.yml, .markdownlint.yaml
Adds markdown linter. Note that current markdown needs corrections and "Markdown Lint " check in this PR will fail, which is actually expected. Markdown is corrected as part of #723
=> Adds Markdown lint action

.github/workflows/checkstyle.yml, config/checkstyle/suppressions-dev.xml, config/checkstyle/suppressions.xml
Changed Checkstyle linter to use uppressions-dev.xml which in turn makes the linter less restrictive. This is unfortunately needed because our source code has still high number of issues and because linter now runs on every PR as GH action, it'd be really hard to submit anything "clear" right now as once you touched any "tainted" file, it'd be like opening pandora box for linter. And then if you'd decide to fix it all in your PR, your original change would get obscured by style fixes.
I also disabled LineLength check in general config as 100 chars limit is problematic.
This is redo of #783
=> Made checkstyle GHA use -dev suppression file

.github/workflows/checkstyle.yml
Reworked GHA to use recent Checkstyle version from JAR so we can have any version we like instead of relying on Ubuntu packaged version.
Ticket: #796
=> Reworked GHA to use recent Checkstyle JAR

tools/CODEOWNERS
Adds CODEOWNERS file so no PR slips by unreviewed.
For more info see: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners
=> Added CODEOWNERS to the repo

README.md, build.gradle.kts
This PR does the following:
Fixes the gradle build problem noted in #827.
Changes the macOS .dmg package name to lowercase, but leaves the .app name as uppercase so the user interface is not changed. Closes #821.
Updates the README to change the case of the dmg.
Updates the README to add a note for macOS users regarding the initial permission to run and the possible firewall question about internet access as discussed in #747.
Improves other English in the README.
I also added a commit to indent the build.gradle.kts file to 2 spaces. It was inconsistent.
Could @maehne and @MarcinOrlowski  please review.
=> Fix gradle build, change mac .dmg name to lower case, and update README

CHANGES.md, src/main/java/com/cburch/logisim/instance/StdAttr.java, src/main/java/com/cburch/logisim/std/io/DotMatrixBase.java, src/main/java/com/cburch/logisim/std/io/extra/Buzzer.java, src/main/java/com/cburch/logisim/std/plexers/BitSelector.java, src/main/java/com/cburch/logisim/std/plexers/Decoder.java, src/main/java/com/cburch/logisim/std/plexers/Demultiplexer.java, src/main/java/com/cburch/logisim/std/plexers/Multiplexer.java, src/main/java/com/cburch/logisim/std/plexers/PlexersLibrary.java, src/main/java/com/cburch/logisim/std/wiring/Transistor.java, src/main/java/com/cburch/logisim/std/wiring/TransmissionGate.java, src/main/java/com/cburch/logisim/std/wiring/WiringLibrary.java, src/main/resources/resources/logisim/strings/std/std.properties, src/main/resources/resources/logisim/strings/std/std_de.properties, src/main/resources/resources/logisim/strings/std/std_el.properties, src/main/resources/resources/logisim/strings/std/std_es.properties, src/main/resources/resources/logisim/strings/std/std_fr.properties, src/main/resources/resources/logisim/strings/std/std_it.properties, src/main/resources/resources/logisim/strings/std/std_ja.properties, src/main/resources/resources/logisim/strings/std/std_nl.properties, src/main/resources/resources/logisim/strings/std/std_pl.properties, src/main/resources/resources/logisim/strings/std/std_pt.properties, src/main/resources/resources/logisim/strings/std/std_ru.properties
Add `SELECT_LOC` to StdAttr.
Changed all Plexers and Transistor/TransmissionGate to use the standard attribute.
Added the attribute to BitSelector, Buzzer and LedMatrix.
One downside is that the Transistor and TransmissionGate are not longer backwards compatible. 
The options changed from `Bottom/Right` and `Top/Left` to `Bottom/Left` and `Top/Right`.
=> Add SELECT_LOC to StdAttr

src/main/java/com/cburch/logisim/soc/jtaguart/JtagUartAttributes.java, src/main/java/com/cburch/logisim/soc/vga/VgaAttributes.java, src/main/java/com/cburch/logisim/util/LocaleManager.java, src/main/resources/resources/logisim/strings/soc/soc.properties, src/main/resources/resources/logisim/strings/soc/soc_de.properties, src/main/resources/resources/logisim/strings/soc/soc_el.properties, src/main/resources/resources/logisim/strings/soc/soc_es.properties, src/main/resources/resources/logisim/strings/soc/soc_fr.properties, src/main/resources/resources/logisim/strings/soc/soc_it.properties, src/main/resources/resources/logisim/strings/soc/soc_ja.properties, src/main/resources/resources/logisim/strings/soc/soc_nl.properties, src/main/resources/resources/logisim/strings/soc/soc_pl.properties, src/main/resources/resources/logisim/strings/soc/soc_pt.properties, src/main/resources/resources/logisim/strings/soc/soc_ru.properties
Adds support for non-localizable options and removes a few elements from localization strings. The rationale: our localizations lag for most of the languages and files are massive. Certain elements like i.e. screen resolutions (`800x600` or element capacity) can be currently made non-translatable with no harm, and benefit of reducing number of localization entries.
=> Adds support for non-localizable options

src/main/java/com/cburch/draw/gui/AttrTableSelectionModel.java, src/main/java/com/cburch/logisim/gui/main/AttrTableSelectionModel.java, src/main/java/com/cburch/logisim/gui/main/AttrTableToolModel.java, src/main/resources/resources/logisim/strings/draw/draw.properties, src/main/resources/resources/logisim/strings/draw/draw_de.properties, src/main/resources/resources/logisim/strings/draw/draw_el.properties, src/main/resources/resources/logisim/strings/draw/draw_es.properties, src/main/resources/resources/logisim/strings/draw/draw_fr.properties, src/main/resources/resources/logisim/strings/draw/draw_it.properties, src/main/resources/resources/logisim/strings/draw/draw_ja.properties, src/main/resources/resources/logisim/strings/draw/draw_nl.properties, src/main/resources/resources/logisim/strings/draw/draw_pl.properties, src/main/resources/resources/logisim/strings/draw/draw_pt.properties, src/main/resources/resources/logisim/strings/draw/draw_ru.properties, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties
This PR reworks messages shown when user adds or selects components on the canvas. It removes "Selection:" prefix from all the `selectionXXX` strings (from all language versions) as this prefix is on real use and just wastes screen space. The same for "Tool:" prefix of `toolAttrTitle` string. It also removes `selectionOne` string completely as after the above change the only sane form of `selectionOne` is `%s` hence no point of having it at all.
=> Selection messages reworked

.github/workflows/nightly.yml
Fixed a bug in git history handing that could cause worker script to fail silently under some circumstances. Also prevented future silent failures and did some cleanup.
I also restored `pull_request` trigger because `schedule` only works if worker is part of main branch (which is not the case unless next release). This is not really a big deal really. We will have occasionally more than one "daily" build per day (with file named the same but different content though) but this is the only minor issue. I could add hash to filename but I do not think it is really worth the efforts really.
Closes #818
=> Reworked nightly builder

CHANGES.md, src/main/java/com/cburch/draw/model/AbstractCanvasObject.java, src/main/java/com/cburch/draw/tools/DrawingAttributeSet.java, src/main/java/com/cburch/logisim/circuit/Circuit.java, src/main/java/com/cburch/logisim/circuit/CircuitAttributes.java, src/main/java/com/cburch/logisim/circuit/appear/AppearancePort.java, src/main/java/com/cburch/logisim/circuit/appear/AppearanceSvgReader.java, src/main/java/com/cburch/logisim/data/AbstractAttributeSet.java, src/main/java/com/cburch/logisim/data/Attribute.java, src/main/java/com/cburch/logisim/data/AttributeSets.java, src/main/java/com/cburch/logisim/data/Attributes.java, src/main/java/com/cburch/logisim/file/XmlReader.java, src/main/java/com/cburch/logisim/file/XmlWriter.java, src/main/java/com/cburch/logisim/soc/jtaguart/JtagUartAttributes.java, src/main/java/com/cburch/logisim/soc/memory/SocMemoryAttributes.java, src/main/java/com/cburch/logisim/soc/nios2/Nios2Attributes.java, src/main/java/com/cburch/logisim/soc/pio/PioAttributes.java, src/main/java/com/cburch/logisim/soc/rv32im/RV32imAttributes.java, src/main/java/com/cburch/logisim/soc/vga/VgaAttributes.java, src/main/java/com/cburch/logisim/std/hdl/VhdlEntityAttributes.java, src/main/java/com/cburch/logisim/std/wiring/PinAttributes.java, src/main/java/com/cburch/logisim/tools/AddTool.java, src/main/java/com/cburch/logisim/vhdl/base/VhdlEntityAttributes.java
In this bug fix following topics are addressed:
1) Placing an input pin on an output pin resulted in a null-pointer exception. This was originated in the sorting algorithm in the xml-writer. Fixed.
2) Hidden attributes that were only used internally were written as "dummy" attribute in the .circ file. This is fixed.
3) Custom appearance used the pin location to connect to the pin in the circuit. In case of an input pin directly placed on an output pin the data-structure would only contain one of the two pins and map the two appearance pin to exactly this pin. This caused when reading in the circuit that one would get multiple appearance pins referencing the same circuit pin. Each time the circuit was written out and read in again, the number of appearance pins would increase. This is …
=> A bug fix for the issues reported in #826

.github/workflows/translations.yml
This PR adds Github Action with translation files (*.properties) linter and checker using [trans-tool](https://github.com/MarcinOrlowski/trans-tool/) I developed specifically for that purpose. Even I tested the linter on LSe files It will most likely still need some tweaking here and there, but since translation files are yet in shape I am configuring this action to report warnings and errors but the action itself will always be successful so merge is not blocked. If you touch translation files, please DO check the linter report (or lint locally with trans-tool).
=> Translation linter

src/main/java/com/cburch/logisim/LogisimVersion.java, src/main/java/com/cburch/logisim/Main.java, src/main/java/com/cburch/logisim/gui/generic/ProjectExplorer.java, src/main/java/com/cburch/logisim/gui/main/Frame.java, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties, src/test/java/com/cburch/logisim/LogisimVersionTest.java
This PR introduces new indicator of project dirty (unsaved) state. Before:
After
One issue (to be fixed later) is that project tree is now showing new marker so it's still `*` used there unless this is fixed.
BLOCKED_BY #888
=> Project "Dirty marker" improved

.github/workflows/dependabot.yml
Adds PR dependency checker. It works around lack of dependent PRs on GitHub. The bot understands `DEPENDS_ON` and `BLOCKED_BY` keywords placed in the PR description and blocks merge of specific PR unless all mentioned dependencies or blockers are not resolved first. Bot can also allow depending on Issues, but that's disabled on purpose. I think having PR that depends on issue that did not produce any PR would cause more problems
Single dependency per item
```
DEPENDS_ON #13 
```
For multiple blockers or dependencies you need this:
```
DEPENDS_ON #15
DEPENDS_ON #176
BLOCKED_BY #114
```
=> Dependabot - dependant PRs workaround

.github/stale.yml
Adds StaleBot config to the project. StaleBot monitor PRs and Issues tagged "incubating", then first pings the authors for an update and eventually closes ticket/PR if no there's still no activity detected after a ping.
=> Adds StaleBot configuration

.github/workflows/checkstyle.yml, build.gradle.kts
[Checkstyle linter has a bug](https://github.com/checkstyle/checkstyle/issues/8929) that causes switch expression to always fail indentation check no matter what you do (you set it to 6, checkstyle reports it should be 8. You edit to make it 8, Checkstyle complains it should be 6 :) This affects our checkstyle action. This PR bumps used version to 8.45.1.
=> Bumps checkstyle version used to address switch expresion related issue.

src/main/java/com/cburch/logisim/std/gates/Buffer.java, src/main/java/com/cburch/logisim/std/gates/ControlledBuffer.java
Although it looks bizar, .not().not() it is the correct way to go about this problem. In the original version the input value was passed directly to the output without any control.
=> This PR addresses point B) in issue #873

build.gradle.kts
This PR replaces all the strings Gradle used as for `ext` stored variable (i.e. `ext.set("myKey", val)`) with const (`ext.set(MY_KEY, val)` reducing risk of typo-driven bugs
=> Replaces string keys with constants in Gradle script

src/main/java/com/cburch/logisim/util/LineBuffer.java
Changed default addRemarkBlock() indentation from 3 to 0 as it is usually included into other blocks, so indentation should be added there.
Fixes #930.
=> Changed default addRemarkBlock() indentation

.github/workflows/nightly.yml
Fixed version number parsing for nightly builds.
Fixes #939
=> Fixed version number parsing

.github/workflows/translations.yml
#934 used nested substitution, which is not supported by all bash implementations/shells.
limitations:
`en` must not be the last language (right most in `settings.properties`).
=> fix mistake made in #934

build.gradle.kts, docs/developers.md
This PR closes #925.
The srcDir change addresses @BFH-ktt1's specific problem in importing the project.
The change to git parameters in genBuildInfo addresses an issue that Eclipse doesn't have the correct current directory for the git command to work when Eclipse invokes the Gradle task.
This PR also adds a note for Eclipse users explaining what they need to do in order to successfully import and build the project.
Could @MarcinOrlowski and @BFH-ktt1 please review this.
=> Fix for Eclipse

.github/workflows/nightly.yml
Removed "pull_request" trigger from config of nightly builder as we got it already merged into master, "schedule" should be sufficient.
=> Removed pull_request trigger from nightly config

gradle.properties
Rationale version from gradle.properties is then used in the app, so even if nightly builder renames artifacts so filename contains no version string, the version string is still visible, so it must clarly indicate it's non-stable build.
=> Added -dev suffix to version string (in develop branch)

.github/workflows/checkstyle.yml
This PR affects only code files. Docs (which are massively CRLFed) are currently left as-is.
=> Added check against using CRLF line ends.

src/main/java/com/cburch/logisim/fpga/hdlgenerator/HDL.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/WithSelectHDLGenerator.java, src/main/java/com/cburch/logisim/std/io/HexDigitHDLGeneratorFactory.java, src/main/java/com/cburch/logisim/util/LineBuffer.java, src/test/java/com/cburch/logisim/LineBufferTest.java
Fixes ArrayOutOfBounds bug introduced in #1061 as this is what gets thrown when you try to `get(x)` from empty LineBuffer.
DEPENDS_ON #1080
* #1061
* #1080
=> Fixes ArrayOutOfBounds bug introduced in #1060

.github/workflows/build.yml, .github/workflows/nightly.yml
The AdoptOpenJDK has been discontinued since July 2021. When using Zulu you get all the latest updated (TCK Tested) builds for all versions of OpenJDK.
=> Using TCK Tested JDK builds of OpenJDK. 

src/main/java/com/cburch/logisim/util/LineBuffer.java, src/test/java/com/cburch/logisim/LineBufferTest.java
Fixed handling of special chars in replacement string in LineBuffer.applyPairs()
* #1097
=> Fixes Linebuffer.applyPairs() handling of special chars in replacement string

src/main/java/com/cburch/logisim/tools/MenuTool.java
Swaps order of rotate left/right context menu items as most people expect clock wise order (left first, right next).
=> Swaps order of rotate left/right context menu items

README.md, build.gradle.kts
This PR addresses issue #1267. Rather than unsign the Mac app, this now signs it with a generic signature. 
The README is also updated with more detailed instructions for launching the app the first time.
I also note that the app-category generated from jpackage in Java 16 is `Unknown`. In Java 17 it is `public.app-category.utilities`. We now switch it to `public.app-category.education` in all cases.
=> Fix macOS signing

build.gradle.kts
This PR simplifies build.gradle.kts by using a text block to create BuildInfo.java.
=> Use text block to generate BuildInfo

src/main/java/com/cburch/logisim/file/LibraryManager.java, src/main/java/com/cburch/logisim/file/XmlWriter.java, src/main/java/com/cburch/logisim/fpga/settings/BoardList.java
I get the exception below when saving in Windows.  It seems like it's an internal Java.String regex issue when a backslash is used as a split String.
I've written a separate 'split' command in the LibraryManager that allows me to save successfully.
Feel free to ignore this pull request if a fix has already been scheduled or my fix breaks Logisim-evolution under Linux.
Cheers,
Andrew
Signed-off-by: Andrew Paterson <andrew.ian.paterson@gmail.com>
=> Fixed LibraryManager.toRelative regex split on backslash exception.

src/main/java/com/cburch/logisim/circuit/Simulator.java
I've discovered I need to know when the simulation propagation 'cycle' starts so I've added a firePropagationStarted event to Simulator that is symmetric with firePropagationCompleted.
I'd really appreciate it if this change could be added into the next release.
Thanks!
Andrew
=> Fire propagation started event

src/main/java/com/cburch/logisim/fpga/data/IoStandards.java
@zdimension was there a reason why you didn't use `final` in those places? (f4c2c035356123ecd56aa5f44e337b60ab426911)
=> add final keyword to constants

src/main/java/com/cburch/logisim/data/Direction.java
This is a followup to comments in PR #1299. I suggested a change in the use of id could make the methods much simpler. I changed the order to east, north, west, south for both the id assignment and the cardinals array. I modified the methods to compute the values with simple expressions.
@maehne asked if this would cause a problem in serialization. Our files contain "east" rather than 0. I checked inputs from as far back as the original Logisim and they load correctly.
I am aware that I changed the return value for toRadians for south. It was -pi/2 and is now 3*pi/2. That value is used only in rotations of graphics contexts so it still works.
=> Clean up Direction

CHANGES.md, src/main/java/com/cburch/logisim/gui/chrono/ChronoPanel.java
Adds handling of `null` arguments, fixing #1336 type of NPEs
* #1336
=> ChronoPanel NPE fix

CHANGES.md, src/main/java/com/cburch/logisim/std/ttl/Ttl7442.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7464.java
Fixed bug preventing TTL 7442, 7443 and 7444 from being placed on the circuit canvas.
Closes #1342
* #1342
=> Fixed TTL 7442, 7443 and 7444 being non-placeable on the circuit canvas.

CHANGES.md, src/main/java/com/cburch/logisim/gui/generic/ProjectExplorer.java
Sub-circuit can now be deleted with `DELETE` key, along with `BACKSPACE` supported so far
DEPENDS_ON #1343
=> Sub-circuit can now be deleted with `DELETE` key, along with `BACKSPACE`

support/Flatpak/com.github.reds.LogisimEvolution.xml
Whenever I update applications, I get the following error:
```
Wrong namespace on document element in '/var/home/TheEvilSkeleton/.local/share/flatpak/exports/share/mime/packages/com.github.reds.LogisimEvolution.xml' (should be http://www.freedesktop.org/standards/shared-mime-info)
```
This warning was caused by https://github.com/logisim-evolution/logisim-evolution/commit/5f2a9d2e18a5177c10ce48934876f2b0647f2ca4#diff-9d30aa366f803208d2f221bfa3d703ac8791f95367ba0fcfd68f1ac5fef79b86R2, which switched from http to https. I reverted that change due to the warning I was getting.
Fixes: https://github.com/flathub/com.github.reds.LogisimEvolution/issues/21
=> Fixes Flatpak namespace related issue

src/main/java/com/cburch/logisim/gui/prefs/WindowOptions.java, src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/java/com/cburch/logisim/tools/WiringTool.java, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_cn.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties
Weirdly enough, when you cancel a left mouse button press-and-drag with a right-click, **no `mouseReleased` event is fired** - not for either mouse button release. This is likely related to Swing.
If you cancel the LMB press with RMB, the `WiringTool` state is as follows:
- `mousePressed` is fired once
- `exists` is true
- `hasDragged` is true if a `mouseMove` was fired before RMB was clicked
- `start` contains the position where LMB was first pressed
As far as the `WiringTool` is concerned, the LMB is still pressed. Then, a second LMB press does the following:
- `mousePressed` tests `exists` (which is true) and calls `mouseDragged` with the position of the second LMB press
- `mouseDragged` sets `hasDragged`, if the mouse cursor position has changed
Thus, the drag continues from the …
=> Fixes for issue #1339 (wire starting position error) and #1277 (UI scale auto button)

src/main/java/com/cburch/logisim/gui/generic/RegTabContent.java
As a vhdl "circuit" does not contain any state, the register tab triggered a NPE. This PR fixes this and addresses #1411
=> Bug fix for #1411

src/main/java/com/cburch/logisim/gui/hex/HexFile.java
In about a week, Java 18 will be released. I tried the release candidate with our code. Java 18 deprecates the use of Runtime.exec(String). This PR replaces the two places in our code that use this method. I did not see any other problems using Java 18 to compile our code.
I was unable to actually test this change. The only place this code is executed is during running the main method of the HexFile class. That method is intended to be a test of the code. However, it fails before even reaching the calls to exec. There are actually four main methods in our code that are likely intended as tests. These should be moved to junit tests or perhaps abandoned. I'll create an issue for this.
=> Fix deprecated Runtime.exec() method for Java 18

src/main/java/com/cburch/logisim/std/memory/RamHdlGeneratorFactory.java
In case of setting the `line-eables` attribute, the OE-pin is removed. However, in the HDL-description it is still there and needs to be connected to a constant 1.
=> Ram OE-pin HDL bugfix. This fixes issue #1421

src/main/java/com/cburch/logisim/gui/hex/HexFile.java
This fixes the problem that caused the "main" test to fail in HexFile as reported in #1414. The problem was introduced about a year ago when cleaning up error handling.
With this change, the test now succeeds. I will now look at moving this test to junit as noted in #1415.
=> Fix problem with reading "v3.0 hex byte addressed" memory

src/main/java/com/cburch/logisim/gui/hex/HexFile.java, src/test/java/com/cburch/logisim/gui/hex/HexFileTest.java
This PR moves the HexFile tests from the HexFile.main() method to junit tests as suggested in #1415. I modified the tests to make them more junit friendly.
In fixing these tests, I found that there were still parts of HexFile that were not compatible with a 64-bit word size. This PR also fixes those issues.
There was a part of HexFile.main() that provided interactive support for testing with existing files. I removed that part as well since I found I could test the same thing by just creating a ROM and reading/writing the value. I did not put that part into junit because it requires a person to select format styles and thus isn't compatible with automated junit testing.
=> Move tests from HexFile.main() to junit and fix uncovered problems

.github/workflows/build.yml, build.gradle.kts
Just noticed the Sonarcloud integration added in 49398d was somehow lost on develop.
=> Restore Sonar CI integration

src/main/java/com/cburch/logisim/circuit/appear/CircuitAppearance.java
In `XmlReader.java`, line 274, there was a test to determine whether a particular circuit had a custom appearance or the default. This function (`hasCustomAppearance()`) is implemented in `CircuitAppearance.java`, line 79.
The algorithm used for `hasCustomAppearance()` ignored pin count and position, among other things. If `hasCustomAppearance()` returned false for a circuit, then the `XmlReader` didn't write an `<appear>` block in the XML - which causes the next file load to erroneously reset the custom appearance of that circuit.
Instead of troubleshooting the algorithm, I opted to remove the test on line 274, since it doesn't seem to be very expensive to have an `<appear>` block for every circuit.
=> (#1379) Fixed unintended shallow copy in CircuitAppearance.java

src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/java/com/cburch/logisim/util/LocaleManager.java
Java 19 will be released in September. I downloaded the release candidate and used it to build LE. It works well, except for deprecation of some constructors for Locale. This PR fixes the deprecated items so LE will compile cleanly in Java 19.
=> Fix Locale constructor deprecations

src/main/java/com/cburch/logisim/data/BitWidth.java
All BitWidth attributes now allow text entry of the number in addition to a smaller drop down menu. There are now three modes:
1. A range is not specified, therefore 1-64 (Value.MAX_WIDTH) is allowed. The menu allows 1..8,16,24,32,64; other values can be entered via the keyboard. This used to display all 64 values via a scrolling menu.
2. A range of 12 or fewer options is specified. The menu allows all options; they can also be entered via the keyboard. This behavior did not change.
3. A range of more than 12 options are specified. No menu is created; values must be entered via the keyboard. This used to display all possible values in the menu, possibly scrolling.
The "prefab" mechanism was slightly enhanced, reducing the number of redundant objects created.
=> improve BitWidth UI

.github/workflows/nightly.yml, README.md, snap/snapcraft.yaml
I added support for [Snap] packages. Our stable build is already available as `*.snap` [here](https://snapcraft.io/logisim-evolution). This PR updated nightly builder to also create `*.snap` packages. 
I disabled pushing such packages to `edge` channel on snapcraft.io as I am not sure this is needed.
* #743
=> Snap builder

README.md
We already list [MacPorts](https://www.macports.org/) and [Homebrew](https://brew.sh/), so I don't see a reason not to mention the other packet manager as well.
The downside of listing these is that we are promoting sources that are not controlled by us. To see why this can be a problem, take a look in #743.
=> Add list of Package Managers to README

README.md
Removed unreliable build status badges that we used to display in the main page. These are not working for a while now despite being set up according to official docs. It'd probably be handy to get rid of them from the `master` branch's `README.md` as well as all they display now is `failed` for `master` and no status for `develop`. We eventually might want them back once figured out how to make them really work.
EDIT: Added PR #1574 for `master` too.
=> Removed unreliable build status badges

README.md
Same as PR #1574 but against `master` to not scare potential new users away.
* #1574
=> Removed unreliable build status badges (for master branch)

src/test/java/com/cburch/logisim/gui/hex/HexFileTest.java
I found a bug in the HexFile memory tests. The tests require memory that starts all zeros, but it was paying attention to the user's setting for randomizing memory. That suddenly caused many tests to fail when I forgot I had changed that setting. This PR fixes it to always create the memory with all zeros.
I also cleaned up the imports and an implicit conversion.
=> Fix HexFile tests to never randomize memory.

.github/workflows/nightly.yml, CHANGES.md, README.md, build.gradle.kts
This PR changes ./gradlew createApp to place the app in build/macOS-arch where arch is the architecture of the build, then createDmg uses that to create a logisim-evolution-version-arch.dmg file. This ensures this architecture's parts are kept separate from the other architecture builds.
This should make it fairly easy to add support for the newer Apple CPUs in our version releases. The nightly is updated to contain the architecture in the name. But we do not yet have a github machine to actually build the Apple architecture in the nightly.
This PR addresses #1584.
@MarcinOrlowski, please have a look at this since you have worked on these parts.
=> Add architecture to macOS and Windows build and package name.

README.md
Since having an outdated official Snap package (Neither `stable` nor `nightly` are up-to-date) is in no way beneficial.
I propose removing the links to it until this gets fixed.
As soon as it gets updated to the current version (3.8.0), I will add the links again.
If this PR gets accepted, I will create another one for the `develop` branch.
=> Remove the link to Snap

.github/dependabot.yml
This PR should cause dependabot to automatically generate a PR for each dependency that needs to be updated. It might be necessary to also apply this to master to turn it on.
Be aware that the only automatic test we do is to build the project.
This addresses the suggestion made by @maehne in #1331.
=> Use dependabot to generate PRs to update dependencies

README.md
It seems that LSe is no longer present in WinGet.
Should this also be removed on the master branch?
=> remove WinGet

.github/dependabot.yml
In #1649, I noted that it might be necessary to make this change in the master branch to trigger it to start running. Since it has not generated any PRs for updates, it does appear to be necessary. Hence this PR.
Note that this should only create update PRs for the develop branch, not master.
=> Use dependabot to generate PRs to update dependencies (master branch)

src/main/java/com/cburch/logisim/util/ZipClassLoader.java
Java 20 will be released soon. As usual, I downloaded the release candidate and built the project. There is one line in our code that is deprecated in Java 20. This PR fixes it as suggested in the Java documentation.
@BFH-ktt1, I think this is code you added. The method is actually tagged to suppress the "unused" warning so it may not even be used and I don't know how to test it. Please check to see that this change makes sense.
=> Fix deprecated URL constructor

.github/CODEOWNERS, .github/dependabot.yml
The reason dependabot is not generating PRs for updates is that I can't type, nor apparently read. I mispelled a keyword the second time it occurs.
I am also adding myself to the CODEOWNERS file since I expect to review the updates in particular. Besides, I've written a lot of reviews.
I took the time to set up a test Project to see exactly what it will do. It is necessary to make the change in master. So there is a paired PR.
=> Fix typo in dependabot.yml and add myself to CODEOWNERS

.gitignore, src/main/java/com/cburch/logisim/fpga/download/Download.java, src/main/java/com/cburch/logisim/fpga/download/DownloadBase.java, src/main/java/com/cburch/logisim/fpga/gui/FpgaClockPanel.java, src/main/java/com/cburch/logisim/fpga/gui/FpgaCommander.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/AbstractHdlGeneratorFactory.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/SynthesizedClockHdlGeneratorFactory.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/SynthesizedClockHdlGeneratorInstanceFactory.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/TickComponentHdlGeneratorFactory.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/ToplevelHdlGeneratorFactory.java, src/main/java/com/cburch/logisim/fpga/hdlgenerator/XilinxSeries7SynthesizedClockHdlGeneratorFactory.java, src/main/java/com/cburch/logisim/gui/start/Startup.java, src/main/java/com/cburch/logisim/std/wiring/ClockHdlGeneratorFactory.java, src/main/resources/resources/logisim/strings/fpga/fpga.properties, src/main/resources/resources/logisim/strings/fpga/fpga_de.properties
I completed an initial attempt to add clock acceleration, or really re-clocking. The FPGA Commander dialog now has a pre multiplier and divider field that will display for Vivado Xilinx Series 7 chips (at this point it's the only thing I could confidently test...others could be added since I created a factory to generate the chip-specific code). An MMCM-based component is inserted into the clock chain. Tested with both Verilog and VHDL generation. If no pre-multiply and pre-divider factors are specified, a simple loopback component is generated. One of the things that is not coded for is that MMCM has parameter requirements that could be specified by the user that would result in synthesis failure. Relates to #1667.
=> Add clock acceleration for Xilinx 7 series

src/main/java/com/cburch/logisim/analyze/model/TruthTable.java
Handles the case where the valid table is imported, but the app throws an error, as described in #517.
New behavior: when identical inputs are found, also check output equality. If outputs are equal, do not throw.
Import valid truth table from #517 
[valid_truth.txt](https://github.com/logisim-evolution/logisim-evolution/files/11184237/valid_truth.txt)
Table imports successfully
Import invalid truth table, where row 5 output is changed to 0
[invalid_truth.txt](https://github.com/logisim-evolution/logisim-evolution/files/11184523/invalid_truth.txt)
=> [TruthTable] don't throw on overlapping inputs with identical output

src/main/java/com/cburch/logisim/std/gates/ControlledBuffer.java, src/main/resources/doc/en/html/libs/gates/controlled.html, src/main/resources/doc/fr/html/libs/gates/controlled.html, src/main/resources/doc/pt/html/libs/gates/controlled.html, src/main/resources/doc/ru/html/libs/gates/controlled.html
Fix for #1725, fix > 1 bit width regression introduced by #1704
[test_controlled_buff_fix_wide_in.zip](https://github.com/logisim-evolution/logisim-evolution/files/11240647/test_controlled_buff_fix_wide_in.zip)
=> Controlled buff wide inputs patch

src/main/resources/doc/de/html/guide/gui/gui-toolsbar.html, src/main/resources/doc/en/html/guide/gui/gui-canvas.html, src/main/resources/doc/en/html/guide/gui/gui-toolsbar.html, src/main/resources/doc/en/html/guide/menu/edit.html, src/main/resources/doc/en/html/guide/subcirc/sub-personalise.html, src/main/resources/doc/pt/html/guide/gui/gui-toolsbar.html, src/main/resources/doc/pt/html/guide/mem/mem-hex.html, src/main/resources/doc/pt/html/guide/subcirc/sub-personalise.html, src/main/resources/doc/ru/html/guide/gui/gui-toolsbar.html
Went through the documentation and changed "Schift" to "Shift" in 12 different instances. Fixes #1687
=> Fixed typo "Schift" to "Shift"

build.gradle.kts
mockito-inline is now included in mockito-core which is a dependency of mockito-junit-jupiter. Thus we do not need to list it in build.gradle.kts.
=> Remove outdated mockito-inline

CHANGES.md, src/main/java/com/cburch/logisim/std/plexers/Multiplexer.java
New pull request for issue #1733.
My guess was essentially spot-on. The select port on the Multiplexer now only adjusts for Narrow size when the number of inputs is greater than 2.
Before:
After:
=> Fixed mispositioned select/enable pins on Multiplexer

.github/dependabot.yml, .github/workflows/build.yml, .github/workflows/checkstyle.yml, .github/workflows/markdown.yml, .github/workflows/nightly.yml, .github/workflows/translations.yml, README.md, docs/developers.md
This should update our actions to work with the renaming of branches. It also updates the documentation to refer to main rather than develop.
=> Update workflows and documentation for changing default branch to main

build.gradle.kts
I have been thinking about the createDistDir task in our build for a while. It is badly named. Its name made sense when I originally created it. But it hasn't been useful for that purpose since I fixed the outfile and outdir settings on the other tasks. Gradle automatically creates the path for those.
Now createDistDir is serving the purpose of cleaning up the libs directory so jpackage doesn't include garbage when building the package.
I started to just change the name. But it seems wrong to have a task that removes other tasks outputs (excepting clean, of course).
So I decided to create a task called createPackageInput that manages its own directory, called packageInput, and ensures it contains no other file than the desired shadowJar.
This seems cleaner to me.
=> Make a createPackageInput target in build

src/main/java/com/cburch/draw/shapes/RoundRectangle.java, src/main/java/com/cburch/logisim/gui/main/TickCounter.java, src/main/java/com/cburch/logisim/std/io/extra/Buzzer.java, src/main/java/com/cburch/logisim/std/io/extra/ProgrammableGeneratorState.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7400.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7402.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7404.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7408.java, src/main/java/com/cburch/logisim/std/ttl/Ttl74125.java, src/main/java/com/cburch/logisim/std/ttl/Ttl74266.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7432.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7434.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7436.java, src/main/java/com/cburch/logisim/std/ttl/Ttl747266.java, src/main/java/com/cburch/logisim/std/ttl/Ttl7486.java
This PR addresses some of the issues noted by CodeQL.
I fixed the TTL issues by changing the type of the loop control variable from byte to int. In all these cases, the loop update adds an integer to the variable. This causes the conversion of the variable to int, the addition, and then conversion of the result to byte (the implicit narrowing conversion) to assign to the variable. The loop body converts the byte back to int to do more calculations and pass the value to integer parameters. It is clearly better to just use integer throughout.
The buzzer has a similar issue. It also has a place where an integer was used in repeated double calculations. In the latter case, I changed the declaration to make that a double throughout.
The TickCounter issue is an intended conversion that I made …
=> Fix some of the narrowing conversions noted by CodeQL

.github/workflows/nightly.yml
Nightly has been running on closed pull requests. When we switched to main as the default branch, it began working as intended at midnight UTC. The original intent was to run it Nightly (hence the name) but that required developing on the default branch. This PR drops running it on closed pull requests so it should only run once per day at midnight.
=> Only run Nightly at midnight, not on closed pull requests

src/main/java/com/cburch/logisim/file/ReaderInputStream.java
This PR fixes the read() method in ReaderInputStream.java as noted in #1770. This method is supposed to implement read() as defined in the Reader class Java documentation. As it was written, it clearly did not.
My research shows that it is unlikely that this method is ever actually called in our program. The only use of this class is in trying to read old original Logisim files. Even there it is only used in a BufferedReader that almost certainly uses one of the methods that reads many bytes at a time. I didn't come up with a test reading old files that got so far as to try this. Still. It is currently incorrect and so I fix it.
=> Fix ReaderInputStream read

src/main/java/com/cburch/logisim/analyze/file/TruthtableTextFile.java
This is another problem noted by codeQL and #1794. After this, there will be one problem remaining.
The problem here is that using the `-` character in square brackets in a pattern generally designates a range. The intent in our code here is clearly to actually match the `-` character since the range `=-|` includes lots of characters including all upper and lower case letters. The standard way to do match just the character is to put the `-` character first in the list. I have modified the code to do that.
=> Fix TruthtableTextFile pattern match

CHANGES.md, src/main/java/com/cburch/logisim/std/memory/Ram.java
This pull request contains simple fixes for the problem described in issue #1747. The main culpirit was the fact that that the code did not discern between error addresses and not fully specified addresses. This also contains a small refactoring of the repeated calls to `state.setPort(RamAppearance.getDataOutIndex(0, attrs), Value.createError(dataBits), DELAY);` to a separate function for the sake of readability.
=> Fixes RAM error output - #1747

src/main/java/com/cburch/logisim/gui/start/TtyInterface.java
This small PR adjusts the TTY interface to load the ram file before doing the first propagation, solving #1338.
Testing with the ram.zip file provided by @ChristopherPAndrews yields 
```
0000 0001
0000 0010
0000 0011
0000 0100
0000 0101
0000 0110
0000 0111
0000 1000
0000 1001
0000 1010
0000 1011
0000 1100
0000 1101
0000 1110
0000 1111
1111 1111
```
as expected.
=> TTY now loads RAM before first propagation - Fixes #1338

src/main/java/com/cburch/logisim/fpga/settings/BoardList.java
This PR fixes the remaining security issue and should close #1794.
=> Fix Zip Slip security issue in reading jar

src/main/java/com/cburch/logisim/gui/prefs/HotkeyOptions.java
I suddenly find that when we change the international settings, the strings in the hotkey tab are not localized timely, because I don't override the `public void localeChanged()` well.  Though after restarting the names are localized, it seems not good to break the original way that all the text are updated as long as the settings change. Now I have fixed the bug. Sorry to disturb.
=> Fix: hotkey names are not localized immediately

.github/CONTRIBUTING.md
This fixes CONTRIBUTING.md to refer to the main branch rather than develop.
=> Update contributing to branch main

src/main/java/com/cburch/logisim/fpga/settings/BoardList.java
Fix #1879 
If we can't resolve the canonical path, then treat it as an error.
I believe this is a minor enough to not require a `CHANGES.md` update.
On a separate note, the contribution guidelines should probably be updated since the there is no branch named **develop**.
=> Canonicalize both paths before comparing

src/main/java/com/cburch/logisim/std/memory/SRFlipFlop.java
Although the behaviour of S-R flip-flops is undefined when both inputs are high, it should be consistent in simulation and HDL export.
Fixes Issue #1874
=> S-R flip-flops behave different in HDL

CHANGES.md, src/main/java/com/cburch/logisim/data/Value.java, src/main/java/com/cburch/logisim/instance/StdAttr.java, src/main/java/com/cburch/logisim/std/arith/FpAdder.java, src/main/java/com/cburch/logisim/std/arith/FpComparator.java, src/main/java/com/cburch/logisim/std/arith/FpDivider.java, src/main/java/com/cburch/logisim/std/arith/FpMultiplier.java, src/main/java/com/cburch/logisim/std/arith/FpNegator.java, src/main/java/com/cburch/logisim/std/arith/FpSubtractor.java, src/main/java/com/cburch/logisim/std/arith/FpToInt.java, src/main/java/com/cburch/logisim/std/arith/IntToFp.java
This is done by converting all 16 bit floats to 32 bit then back to 16 bit. Conversion functions were validated against `Float.float16ToFloat()` and `Float.floatToFloat16()` available in Java 20 and later. In the future if updated to use Java 20 or newer would recommend switching to built in functions.
This relates to #1610 
Attached is the conversion validation file, which only runs in Java 20 or newer. I am not sure if there is a better way to store it or if it is even needed.
[Main.txt](https://github.com/logisim-evolution/logisim-evolution/files/12741860/Main.txt)
=> Adding 16 bit float support

src/main/java/com/cburch/logisim/analyze/model/Implicant.java, src/test/java/com/cburch/logisim/analyze/model/ImplicantTest.java
As described in issue #1889, some combinational formulae are not being fully minimized.
I've determined that this happens only if the McKluskey algorithm is not able to determine the best minimal cover. It appears that the current greedy algorithm sometimes does not select a minimal cover and can even include primes that are completely covered by other primes.
**What I have done:**
In order to fix this I implemented Petrick's Method. I implemented Petrick's Method in the same way as described on wikipedia([https://en.wikipedia.org/wiki/Petrick%27s_method](https://en.wikipedia.org/wiki/Petrick%27s_method)).
Before & after comparison: (Formulae from #1889)
1. Formula: bc'd+a'b'd'+a'b'c+a'cd'+b'c'd'+ab'd+ac'+bcd'
Current Minimization: …
=> Fix combinational analysis not fully minimizing

src/main/java/com/cburch/logisim/gui/main/Canvas.java
This PR is for my issue #1946.
I've implemented key combinations CTRL + and CTRL - (both in the main block of the keyboard and the num-pad).
The zooming will be done similarilly to CTRL-Scroll zooming towards the mouse cursor. Should the mouse cursor not be on the canvas the zoom will zoom towards the center. For that I created a new method doZoom() that handles this zooming for both CTRL-Scroll and the new combinations.
=> Enable zooming by key combination

.github/workflows/build.yml
This PR provides for a SONAR_HOST_URL secret to be passed to SonarQube. It silences SonarQube until that secret is provided.
=> Add sonar host url to sonarqube build step

src/main/java/com/cburch/logisim/analyze/gui/Analyzer.java
This PR removes the main test method from Analyzer. In PR #1938, @superenginegit provided JUnit test cases for this piece of code. Thank you, @superenginegit.
This completes the examination and removal of main methods used as test tools, by moving the testing to JUnit. It therefore closes issue #1415.
=> Remove main method from Analyzer

CHANGES.md, src/main/java/com/cburch/logisim/gui/generic/AttrTable.java
Fixes #618 
The table in the "Properties" section would enter edit mode on any key press event if an editable cell in the table was clicked. This behaviour resulted in triggering two events simultaneously, causing unintended behaviour.
The fix implemented in this PR ensures that the table enters edit mode only when triggered by a mouse click or the space key. This change resolves the issue as intended.
=> Fix: multiple keyevent actions removal

.github/workflows/nightly.yml, build.gradle.kts
I described in #1997 the Nightly upload issues this PR should fix.
=> Update to have nightly build both x86_64 and aarch64 Mac versons.

src/main/java/com/cburch/draw/toolbar/ToolbarButton.java, src/main/java/com/cburch/logisim/circuit/SplitterFactory.java, src/main/java/com/cburch/logisim/gui/generic/ProjectExplorer.java, src/main/java/com/cburch/logisim/gui/icons/BaseIcon.java, src/main/java/com/cburch/logisim/gui/icons/GroundIcon.java, src/main/java/com/cburch/logisim/gui/icons/PowerIcon.java, src/main/java/com/cburch/logisim/gui/icons/PullResistorIcon.java, src/main/java/com/cburch/logisim/gui/icons/SelectIcon.java, src/main/java/com/cburch/logisim/gui/icons/SplitterIcon.java, src/main/java/com/cburch/logisim/gui/icons/TransistorIcon.java, src/main/java/com/cburch/logisim/gui/icons/TransmissionGateIcon.java, src/main/java/com/cburch/logisim/gui/main/LayoutToolbarModel.java, src/main/java/com/cburch/logisim/gui/prefs/WindowOptions.java, src/main/java/com/cburch/logisim/instance/InstanceFactory.java, src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/java/com/cburch/logisim/std/wiring/Ground.java, src/main/java/com/cburch/logisim/std/wiring/Power.java, src/main/java/com/cburch/logisim/std/wiring/PullResistor.java, src/main/java/com/cburch/logisim/std/wiring/Transistor.java, src/main/java/com/cburch/logisim/std/wiring/TransmissionGate.java, src/main/java/com/cburch/logisim/tools/WiringTool.java, src/main/resources/resources/logisim/strings/gui/gui.properties
Affects all unicoloured icon draws and some multicoloured icons as well as replacing some of the GIF icons with paint icon functions. Fixes #641
=> Added the ability to change the colour of icons

README.md
This pull request adds a reference to the `logisim-evolution` package on nixpkgs to the README.md, as it is already available there.
It also updates the copyright year to 2024.
=> Add nixpkgs reference

src/main/java/com/cburch/logisim/std/memory/Ram.java
Changed the mask used on byte-enabled writes as to use a long literal instead of an integer literal.  This prevents undesired shift behaviour when said literal is shifted and then assigned to the mask long variable. This in turn prevents undesired byte-enable writes on RAM modules with 64-bit long words 
See issue: #2021
=> RAM Module - Fixed byte-enable mask (literal cast)

build.gradle.kts
Since we are now using Java 21, it is possible to simplify the aarch64 Mac build.
After this PR, the only addition to the jpackage Mac application build is the addition of the NSSupportsAutomaticGraphicsSwitching setting for the x86_64 build. It is not required on aarch64 because there no external GPU on those computers.
=> Simplify Mac build, particularly on aarch64 architecture.

src/main/java/com/cburch/logisim/data/Attributes.java, src/main/java/com/cburch/logisim/data/BitWidth.java, src/main/java/com/cburch/logisim/vhdl/base/VhdlEntityAttributes.java
This pull request fixes issue #1979 by adding the upper or lower bound in the error message when the user enters a number that is out of the allowed bounds of the input field.
=> Added bound limits to exception message popups

src/main/resources/doc/de/html/libs/mem/flipflops.html, src/main/resources/doc/en/html/libs/mem/flipflops.html, src/main/resources/doc/zh/html/libs/mem/flipflops.html
"Asynchronous set: When 1 or undefined, this input has no effect." -> "Asynchronous set: When 0 or undefined, this input has no effect."
I took the risk of changing the Chinese version as well, despite not speaking Chinese, as it showed up when searching for the string with grep and it seemed a safe enough change to make to the translation based on Google translate ("0" changed to "1").
=> Minor fix to flipflop documentation.

build.gradle.kts
This restores the older rsyntaxtextarea version so that the build works. I decided to put up a PR to speed up getting the build to work.
First step of #2088.
=> Move rsyntaxtextarea back to 3.5.1.

support/Flatpak/com.github.reds.LogisimEvolution.desktop
Add a main category `Education`  in the `logisim-evolution.desktop` (see [Registered Categories](https://specifications.freedesktop.org/menu-spec/latest/category-registry.html)). Otherwise, the software will be classified as "Unknown Category" in the KDE desktop environment.
=> fix(logisim-evolution.desktop): add main category

src/main/java/com/cburch/logisim/gui/test/TestBench.java
This PR fixes the program freezing whenever the `--test-circuit` command-line option is used, for instance:
```
java -jar logisim-evolution-4.0.0dev-all.jar --test-circuit testbench.circ
```
The problem is in the part at `TestBench.java` that starts the VHDL simulator: it calls `VhdlSimulatorTop.enable` and waits in a loop for the simulator to switch to a state other than `State.DISABLED`. The sequence of states when starting the simulator is:
- starts with `State.ENABLED`,
- if `VhdlSimulatorTop.hasVhdlComponent` returns true, switch to `State.STARTING` and start the simulator process,
- if the process starts sucessfully, switch to `State.RUNNING`,
so the correct way would be to check if the simulator has switched to `State.STARTING` and in this case wait for the state to switch to …
=> Fix --test-circuit

CHANGES.md, src/main/java/com/cburch/logisim/gui/generic/TikZInfo.java, src/main/java/com/cburch/logisim/gui/generic/TikZWriter.java, src/main/java/com/cburch/logisim/std/wiring/Pin.java
Two changes in this PR. First up: correcting the disjoint corners at the transition between the rectangular body of arrow-style pins and their pointed arrow end. The culprit behind this visual issue was pretty easy to find: all five sides of this pointed shape were being drawn individually, instead of as a connected polygon. Here's a before-and-after comparison:
The second bug I addressed in this PR wasn't visual, but rather technical. In my experiments with vector output files, I noticed something funny happening with rectangular-shaped "input" pins. Even though the drawing code in `Pin::drawInputShape()` was calling `drawRect()`, the vector output files were _not_ outputting actual rectangles. Instead, the vector output contained four individual edges laid out sequentially in each place …
=> Fixing the appearance of arrow-style Pins

CHANGES.md, src/main/java/com/cburch/logisim/gui/generic/TikZInfo.java
The first thing I noticed, and tried to correct, was the lack of what I call "arc-length normalization" in Logisim's vector export code. In basic terms, you want to constrain the x-radius and y-radius of the curvature of the corners of rectangles to specific maximums: The x-radius should be no greater than half the width of the rectangle, and the y-radius should be no greater than half the height of the rectangle.
Now, the SVG standard actually demands this behavior explicitly, so if you exported an SVG from Logisim that contained rectangles with rounded corners, the results coming out of Logisim could contain some larger-than-correct radii, but standards-compliant SVG renderers would notice the problem, and correct it without even telling you. However, no such auto-correction exists in …
=> Improved Rounded Rectangles in TikZ image export

src/main/java/com/cburch/logisim/circuit/Propagator.java
This PR changes the default simulation event queue to be Java's PriorityQueue.
It fixes issue #2182.
=> Use Java's PriorityQueue for simulation event queue.

src/main/java/com/cburch/logisim/gui/menu/ProjectCircuitActions.java
This PR is a fix to Import a VHDL entity from a file. It was not working as expected.
To reproduce the issue, go to the menu `Project -> Import VHDL Entity...` and select a valid VHDL file. Nothing will happen, and the entity won't be imported.
Interestingly, this issue was introduced in an old PR #772 and appears to have gone unnoticed until now. This seems like an important feature for anyone working with VHDL in Logisim, so restoring this functionality is essential.
=> fix import VHDL entity from menu Project

build.gradle.kts
This PR fixes the following deprecation warning:
```
w: file:///[...]/logisim-evolution/build.gradle.kts:198:1: 'task(String, noinline type.() -> Unit): type' is deprecated. Use tasks.register instead
```
=> Fix gradle deprecation warning on task

src/main/java/com/cburch/logisim/gui/generic/RegTabContent.java
RegTabCounter was leaving register information on the screen after switching to another circuit. This PR adds a repaint of the panel so old information is removed.
It also changes the way watchers are built so they are built in a regular ArrayList and then transferred to the watchers list in a single action. That reduces the number of times the copyOnWriteArrayList copies itself.
=> RegTabCounter now redraws on clear

src/main/java/com/cburch/logisim/gui/generic/AttrTable.java
Fixed https://github.com/logisim-evolution/logisim-evolution/issues/1983
This issue was being caused by the `focusLost` function in `CellEditor`, which contains a call to `stopCellEditing`.
When the `focusLost` function calls `stopCellEditing` and there is an invalid input, `stopCellEditing` throws an error and opens a new window. The new windows causes the `focusLost` function to call again, which leads to the repeat call to `stopCellEditing`, causing a duplicate warning message.
This fix makes it so any call to `stopCellEditing` is only executed if `stopCellEditing` is not currently in progress, preventing duplicate calls.
=> Fixed double warning message

.github/workflows/nightly.yml, build.gradle.kts
Adds a .zip distribution alongside the existing MSI installer. Useful for users who can’t or don’t want to run an installer, and just need a quick unpack-and-run option.
=> build self-contained archive for windows

src/main/java/com/cburch/logisim/circuit/Propagator.java, src/main/java/com/cburch/logisim/gui/prefs/ExperimentalOptions.java, src/main/java/com/cburch/logisim/prefs/AppPreferences.java, src/main/java/com/cburch/logisim/util/LinkedQueue.java, src/main/java/com/cburch/logisim/util/QNode.java, src/main/java/com/cburch/logisim/util/QueueOfQueues.java, src/main/java/com/cburch/logisim/util/SplayQueue.java, src/main/resources/doc/en/html/guide/prefs/pref-exp.html, src/main/resources/resources/logisim/strings/gui/gui.properties, src/main/resources/resources/logisim/strings/gui/gui_de.properties, src/main/resources/resources/logisim/strings/gui/gui_el.properties, src/main/resources/resources/logisim/strings/gui/gui_es.properties, src/main/resources/resources/logisim/strings/gui/gui_fr.properties, src/main/resources/resources/logisim/strings/gui/gui_it.properties, src/main/resources/resources/logisim/strings/gui/gui_ja.properties, src/main/resources/resources/logisim/strings/gui/gui_nl.properties, src/main/resources/resources/logisim/strings/gui/gui_pl.properties, src/main/resources/resources/logisim/strings/gui/gui_pt.properties, src/main/resources/resources/logisim/strings/gui/gui_ru.properties, src/main/resources/resources/logisim/strings/gui/gui_zh.properties
This PR gives the user a choice of five simulation queues as discussed in issue #2182. The choice is made from the Experimental Tab in preferences. It applies to all projects loaded after the setting is made.
The English version of the documentation for the Experimental Tab is modified to describe the choices. I cannot modify the documentation in other languages.
This PR does not change the default simulation queue which remains the Java PriorityQueue.
=> Add QueueOfQueues and allow user choice of simulation queue.

src/main/java/com/cburch/logisim/gui/log/Signal.java
Fixed https://github.com/logisim-evolution/logisim-evolution/issues/2005
This issue was being caused by a problem allocating new blocks in the `Signal` class, which after fixing revealed a second problem with resizing existing blocks.
Issue 1: The updated `val2` and `dur2` arrays were initialized with a length of `c+1`, and a new block was created at the end of the array at position index `c+1`. However arrays are indexed starting from `0`, and `c+1` is outside the bounds of the array. We should instead add this block at `c`.
Issue 2: When resizing to increase the size of an empty array, the `resize` function would not update the capacity of the existing blocks. Leading to the `Signal` class attemping to access outside the bounds of the array when calling the `extend` function. This can …
=> Fixed resizing issue

src/main/java/com/cburch/logisim/circuit/CircuitAttributes.java
=> Circuit instances cannot have a appearance attribute, as this is set by the circuit itself (static attribute)

src/main/java/com/cburch/logisim/circuit/CircuitState.java
This PR fixes issue #2264. I made a mistake in one line of code while backporting from @kevinawalsh's Holycross fork.
=> Fix bug in CircuitState copyFrom with subcircuits.

src/main/java/com/cburch/logisim/std/io/DipSwitch.java
This change modifies the DIP switch component to allow a minimum width of 1 instead of 2.
Summary of changes:
- Updated MIN_SWITCH in src/main/java/com/cburch/logisim/std/io/DipSwitch.java from 2 to 1.
- Added an inline comment explaining the change.
- Verified rendering, bounds, port positioning, and validation logic all work for width=1.
- Successfully built and ran the application to confirm no regressions.
Enables creation of single DIP switches for simple on/off controls and single-bit teaching examples.
Fixes #2198
=> Allow DIP switch minimum width of 1

src/main/java/com/cburch/logisim/gui/start/MacOsAdapter.java
In checking memory changes, I was creating new projects, adding memory components and then I would just quit and discard. But one time I wanted to try something else and hit cancel rather than discard after quit. Rather than take me back to the project, the program simply quit.
So this PR fixes a long time bug on the Mac where it quits rather than cancels the quit.
=> Fix Quit followed by Cancel on the Mac.

build.gradle.kts
The version of SonarQube that dependabot gave does not exist in the repository. This updates it.
=> Fix SonarQube failure.

src/main/java/com/cburch/logisim/std/gates/PlaTable.java
=> Regression: PLA tables cant load rows with `x` aka DONT_CARE in any bit

.github/workflows/nightly.yml
This PR adds building Arm based Linux installers during our nightly runs.
I looked to see if Github had added Linux-arm runners after reviewing PR #2332. I found them and I noted there that I had tested the PR using Github runners. I also noted testing PR #2343 where I also used the Linux-arm runners.
I also tried to add the Windows-arm runner, but it failed because that runner does not have the WiX Toolset installed, but JPackage depends on it. I couldn't see how to install that package in the runner so I commented out that part. If anyone knows how to install WiX 3.14 from the WIndows command line, we can try it. Alternatively, if we could install WiX 4.0 and upgrade to Java 24, we might make it work.
=> Add Linux Arm builds to Nightly.

build.gradle.kts, gradle.properties
This PR updates our build to be compatible with the Gradle configuration cache. A lot of changes were required, but the overall build still works the same as before.
The PR removes references to the gradleBuilder object from the `doLast` closures and the functions they call.
The PR moves all the functions to an object I called `func` because it complained about using `this.funcname` to call them since `this` is gradleBuilder (whether or not `this` was explicit). But I could call them with `func.funcname`. The `func` object makes no reference to its enclosing environment (which would be gradleBuilder). That is why it declares its own logger.
The PR moves references to our global information to the setup portion of the task and passes the information through constant `val` objects, since …
=> Upgrade build.gradle.kts for Gradle configuration-cache.
